### ISSUE TITLE
Jellyfin 下番剧季度名获取不正确，覆盖获取的剧集信息不反映到界面。

### ISSUE THREAD

**Issue by Lancercmd** [kookxiang/jellyfin-plugin-bangumi#126]
Jellyfin 版本 `10.9.2` ，Bangumi 插件版本 `1.6.0.0`，设置为 `使用 Bangumi 词条作为季名称` `始终根据配置的 Bangumi ID 获取元数据` `转换元数据信息中的换行符` `使用 AnitomySharp 猜测集数`

任意番剧，在正常情况下能获取季度标题为 `第 1 季` 的，在首次获取或尝试覆盖获取元数据的时候，会获取为 `我的朋友很少 Add-on disk` 。可以直接将错误的季度标题修改为 `第 1 季` ，但尝试覆盖获取元数据的时候，会被以 `我的朋友很少 Add-on disk` 覆盖。
> 我的媒体库里实际上确实有 `我的朋友很少 Add-on disk` ，所以尝试复现的话也可能会是别的。

且当剧集没有正确刮削时，不会关联 `bangumiid` 并且也就不会获取元数据（这个是正常的），手动关联 `bangumiid` 后使用覆盖获取元数据时，可以从终端看到获取到的和 `bangumiid` 所关联的具体剧集信息（及nfo文件的内容）是正确的，但更新后的信息不会反映到 Jellyfin 界面中。
> 这个可能是 Jellyfin 本身的问题，但还是一并提一下。

**Comment by kookxiang** [comment]
已知更新到 10.9.x 会有这个问题，临时方法是删除 nfo 文件再刷新元数据

**Comment by Lancercmd** [comment]
> 已知更新到 10.9.x 会有这个问题，临时方法是删除 nfo 文件再刷新元数据

试了下剧集信息确实能反映了，但季度标题的问题依旧。

**Comment by wuyu8512** [comment]
> 季度标题的问题，目前更新 Bangumi 插件到 `1.6.1.0` 后解决了，但在尝试为番剧获取元数据时，会于终端打印以下错误日志。

我也遇到了，看了一下，发现Jellyfin传过来的 `SeasonInfo.Path` 是 `null`

**Comment by Lancercmd** [comment]
> 试试 10.9.4 版本看看？我试了下重启好像也没问题了

我这儿试了依旧会报错，Jellyfin 的要先删除 nfo 才会更新界面的问题也存在。然后还发现计划任务的扫描媒体库变成了对所有媒体获取元数据？
```
[07:43:10] [ERR] [86] MediaBrowser.Providers.TV.SeasonMetadataService: Error in Bangumi
System.ArgumentNullException: Value cannot be null. (Parameter 'path')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at Emby.Server.Implementations.Library.LibraryManager.FindByPath(String path, Nullable`1 isFolder)
   at Jellyfin.Plugin.Bangumi.Providers.SeasonProvider.GetMetadata(SeasonInfo info, CancellationToken token)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```

**Comment by kookxiang** [comment]
发现 10.9.4 的问题越来越严重了，有种想降级回 10.8.x 的冲动

**Comment by moondigi** [comment]
刚更新到10.9.6，同样有类似错误
```
[2024-06-07 09:59:38.034 +08:00] [ERR] [32] MediaBrowser.Providers.TV.SeasonMetadataService: Error in "Bangumi"
System.ArgumentNullException: Value cannot be null. (Parameter 'path')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at Emby.Server.Implementations.Library.LibraryManager.FindByPath(String path, Nullable`1 isFolder)
   at Jellyfin.Plugin.Bangumi.Providers.SeasonProvider.GetMetadata(SeasonInfo info, CancellationToken token)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```

**Comment by RandomNamer** [comment]
> ```
> [14:54:52] [ERR] [71] MediaBrowser.Providers.TV.SeasonMetadataService: Error in Bangumi
> System.FormatException: The input string '' was not in a correct format.
>    at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
>    at Jellyfin.Plugin.Bangumi.Providers.SeasonProvider.<>c.<GetMetadata>b__10_1(BaseItem x)
>    at System.Linq.Enumerable.MaxBy[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IComparer`1 comparer)
>    at Jellyfin.Plugin.Bangumi.Providers.SeasonProvider.GetMetadata(SeasonInfo info, CancellationToken token)
>    at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
> ```

我这边在JF 10.8.13插件1.5.18也一直会报这个错误，[改一下就好了](https://github.com/RandomNamer/jellyfin-plugin-bangumi/commit/8a8f31260252e0aa71d356feeeae2f2dfd1e0fb0)。顺便也很好奇为啥别人之前都还能用季度识别，跑到`int.Parse(string.Empty)`不是一定会出错的嘛......
