### ISSUE TITLE
bangumi登录授权错误

### ISSUE THREAD

**Issue by MATRIX06060** [kookxiang/jellyfin-plugin-bangumi#132]
bgm.tv的登陆授权变成了这个样子
![image](https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/119382805/490bdcf7-b81f-41da-9985-d472a68dc0bf)
![image](https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/119382805/1725ea60-7be7-4aae-a709-46970f4b0eb1)

**Comment by kookxiang** [comment]
发一下 500 期间的日志

**Comment by Joackk** [comment]
> 发一下 500 期间的日志

日志部分在哪啊？我也遇到了一样的情况

**Comment by Joackk** [comment]
@kookxiang 如果是jellyf的日志的话
[Log.txt](https://github.com/user-attachments/files/16048423/Log.txt)

**Comment by Joackk** [comment]
> 发一下 500 期间的日志

[2024-07-01 13:55:13.700 +08:00] [ERR] [37] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/Plugins/Bangumi/OAuth".
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: NotTimeValid
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jellyfin.Plugin.Bangumi.OAuth.OAuthController.OAuthCallback(String code, String user)
   at lambda_method1178(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2024-07-01 13:55:13.708 +08:00] [WRN] [37] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://192.168.31.39:8096/Plugins/Bangumi/OAuth?user=c245d784aebe40469e0caf4af30a3048&code=6bda2be9626ff8a4673e04f858ab7ecb43fdab36" to "192.168.31.109" in 0:00:01.0819083 with Status Code 500

**Comment by kookxiang** [comment]
直接访问一下 https://bgm.tv 看看？感觉大概率是被 DNS 污染了

**Comment by Joackk** [comment]
> 直接访问一下 https://bgm.tv 看看？感觉大概率是被 DNS 污染了

我搜了这个问题，倒是有几个类似的，似乎是证书问题？我用的自签名证书，他好像会校验使用的证书是不是可信的

**Comment by Joackk** [comment]
@kookxiang 我用了最新版的jellyfin和插件还是存在一样问题吗，应该是证书导致的，我用的是自签名证书，看到似乎有一篇类似问题的文章，大佬看看是否有帮助？https://blog.csdn.net/qq_37655399/article/details/125672387

**Comment by Joackk** [comment]
感谢大佬，似乎是代理+NDS的问题，我把nas的DNS改成了谷歌的，然后把代理也关了，正常授权了

**Comment by Dylanaster** [comment]
大佬，麻烦看看我的，也是同样的错误

![Uploading image.png…]()

**Comment by kookxiang** [comment]
超时，多试几次或者给 jellyfin 挂梯子

**Comment by Jasoncnnn** [comment]
> 感谢大佬，似乎是代理+NDS的问题，我把nas的DNS改成了谷歌的，然后把代理也关了，正常授权了

大佬，咋解决的啊，我看了下日志也是访问超时，网页打开bgm.tv是没问题的，没挂梯子

**Comment by Jasoncnnn** [comment]
> > 感谢大佬，似乎是代理+NDS的问题，我把nas的DNS改成了谷歌的，然后把代理也关了，正常授权了
> 
> 大佬，咋解决的啊，我看了下日志也是访问超时，网页打开bgm.tv是没问题的，没挂梯子

我靠，刚说完，然后开启ipv6就能授权了。。

**Comment by Joackk** [comment]
> > > 感谢大佬，似乎是代理+NDS的问题，我把nas的DNS改成了谷歌的，然后把代理也关了，正常授权了
> > 
> > 
> > 大佬，咋解决的啊，我看了下日志也是访问超时，网页打开bgm.tv是没问题的，没挂梯子
> 
> 我靠，刚说完，然后开启ipv6就能授权了。。

感觉是DNS解析问题，可能是被污染了
