### ISSUE TITLE
emby无法正确刮削里番数据 [附日志]

### ISSUE THREAD

**Issue by ll2963336** [kookxiang/jellyfin-plugin-bangumi#133]
+ 运行配置
1. windows 10 64位
2. Emby version: 4.9.0.25
3. Emby.Plugin.Bangumi version: 1.6.1 (CI 最新版 -> Emby Plugin -> bumped to 1.6.1 处获取)
4. 授权 &【取消勾选】忽略NSFW内容（如图所示）

![image](https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/37789416/49a66899-30a4-4fdc-ad3e-8420d47c5120)

+ 日志
```
2024-06-19 23:02:30.248 Info HttpClient: GET https://api.bgm.tv/v0/subjects/492041
2024-06-19 23:02:30.599 Error ProviderManager: SubjectImageProvider failed in GetImageInfos for type Series
*** Error Report ***
Version: 4.9.0.25
Command line: C:\Users\nasnas\AppData\Roaming\Emby-Server\system\EmbyServer.dll -noautorunwebapp
Operating system: Microsoft Windows 10.0.19044
OS/Process: x64/x64
Framework: .NET 8.0.5
Runtime: C:/Users/nasnas/AppData/Roaming/Emby-Server/system/System.Private.CoreLib.dll
Processor count: 8
Data path: C:\Users\nasnas\AppData\Roaming\Emby-Server\programdata
Application path: C:\Users\nasnas\AppData\Roaming\Emby-Server\system
Jellyfin.Plugin.Bangumi.BangumiApi+ServerException: Jellyfin.Plugin.Bangumi.BangumiApi+ServerException: Not Found: resource can't be found in the database or has been removed
at Jellyfin.Plugin.Bangumi.BangumiApi.ServerException.ThrowFrom(HttpResponseInfo response)
at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest(String method, HttpRequestOptions options)
at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest[T](String url, CancellationToken token)
at Jellyfin.Plugin.Bangumi.BangumiApi.GetSubject(Int32 id, CancellationToken token)
at Jellyfin.Plugin.Bangumi.ExternalIdProvider.SubjectImageProvider.GetImages(BaseItem item, LibraryOptions libraryOptions, CancellationToken token)
at Emby.Providers.Manager.ProviderManager.GetImages(RemoteImageFetchOptions options, CancellationToken cancellationToken, IRemoteImageProvider provider, Int32 providerIndex)
Source: Emby.Plugin.Bangumi
TargetSite: Void MoveNext()
```

**Comment by kookxiang** [comment]
https://github.com/kookxiang/jellyfin-plugin-bangumi/actions/runs/9596758424
可以试试这个版本

**Comment by emojerGong** [comment]
大佬您提供的版本有试过了，从结果上看依旧不行，以下是该版本的情况：

+ 第一次刮削请求（日志表述的好像是相同报错）：
```
2024-06-20 22:47:03.325 Info HttpClient: GET https://api.bgm.tv/v0/subjects/492041
2024-06-20 22:47:03.685 Error ProviderManager: SubjectImageProvider failed in GetImageInfos for type Series
*** Error Report ***
Version: 4.9.0.25
Command line: C:\Users\nasnas\AppData\Roaming\Emby-Server\system\EmbyServer.dll -noautorunwebapp
Operating system: Microsoft Windows 10.0.19044
OS/Process: x64/x64
Framework: .NET 8.0.5
Runtime: C:/Users/nasnas/AppData/Roaming/Emby-Server/system/System.Private.CoreLib.dll
Processor count: 8
Data path: C:\Users\nasnas\AppData\Roaming\Emby-Server\programdata
Application path: C:\Users\nasnas\AppData\Roaming\Emby-Server\system
Jellyfin.Plugin.Bangumi.BangumiApi+ServerException: Jellyfin.Plugin.Bangumi.BangumiApi+ServerException: Unauthorized: invalid http Authorization header, missing scope or missing token
at Jellyfin.Plugin.Bangumi.BangumiApi.ServerException.ThrowFrom(HttpResponseInfo response)
at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest(String method, HttpRequestOptions options)
at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest[T](String url, String accessToken, CancellationToken token)
at Jellyfin.Plugin.Bangumi.BangumiApi.GetSubject(Int32 id, CancellationToken token)
at Jellyfin.Plugin.Bangumi.ExternalIdProvider.SubjectImageProvider.GetImages(BaseItem item, LibraryOptions libraryOptions, CancellationToken token)
at Emby.Providers.Manager.ProviderManager.GetImages(RemoteImageFetchOptions options, CancellationToken cancellationToken, IRemoteImageProvider provider, Int32 providerIndex)
Source: Emby.Plugin.Bangumi
TargetSite: Void MoveNext()
```

+ 第二次刮削请求，发现token过期，重新授权失败，报以下错误
```
Failed to handle bangumi callback: Unauthorized: invalid http Authorization header, missing scope or missing token
```

**Comment by kookxiang** [comment]
https://github.com/kookxiang/jellyfin-plugin-bangumi/actions/runs/9625806244
我的问题，再试试这个版本呢？

**Comment by emojerGong** [comment]
感谢大佬。这个版本结果上看也是不行，日志上看卡在授权相关上面

> bangumiLite版本号：`1.6.0.0`

+ 执行已下操作&弹出信息
1. 授权 (url:`http://localhost:7000/Bangumi/OAuth?user=省略&code=省略`)，报`Failed to handle bangumi callback: Unauthorized: need Login`
2. 刷新授权页面，报`{"error":"invalid_grant","error_description":"Authorization code doesn't exist or is invalid for the client"}`

+ 日志如下
```
2024-06-22 21:40:24.272 Debug Server: http/1.1 GET http://localhost:7000/emby/Bangumi/Redirect?prefix=http://localhost:7000&user=省略. Source Ip: ::1, UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0
2024-06-22 21:40:24.273 Debug Server: http/1.1 Response 302 to ::1. Time: 1ms. GET http://localhost:7000/emby/Bangumi/Redirect?prefix=http://localhost:7000&user=省略
2024-06-22 21:40:26.227 Debug Server: http/1.1 GET http://localhost:7000/Bangumi/OAuth?user=省略&code=省略. Source Ip: ::1, UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0
2024-06-22 21:40:26.228 Info HttpClient: POST https://bgm.tv/oauth/access_token
2024-06-22 21:40:26.749 Info HttpClient: GET https://api.bgm.tv/v0/me
2024-06-22 21:40:27.349 Error App: Unauthorized: need Login
2024-06-22 21:40:27.351 Error Server: Error processing request
	*** Error Report ***
	Version: 4.9.0.25
	Command line: C:\Users\nasnas\AppData\Roaming\Emby-Server\system\EmbyServer.dll -noautorunwebapp
	Operating system: Microsoft Windows 10.0.19044
	OS/Process: x64/x64
	Framework: .NET 8.0.5
	Runtime: C:/Users/nasnas/AppData/Roaming/Emby-Server/system/System.Private.CoreLib.dll
	Processor count: 8
	Data path: C:\Users\nasnas\AppData\Roaming\Emby-Server\programdata
	Application path: C:\Users\nasnas\AppData\Roaming\Emby-Server\system
	System.InvalidOperationException: System.InvalidOperationException: StatusCode cannot be set because the response has already started.
	   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ThrowResponseAlreadyStartedException(String value)
	   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.set_StatusCode(Int32 value)
	   at Emby.Server.Implementations.Services.ResponseHelper.WriteToResponse(HttpListenerHost httpListenerHost, IResponse response, IRequest request, IStreamHelper streamHelper, Object result, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IServerApplicationHost appHost, IRequest httpReq, IResponse httpRes, IStreamHelper streamHelper, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
	Source: Microsoft.AspNetCore.Server.Kestrel.Core
	TargetSite: Void ThrowResponseAlreadyStartedException(System.String)
	
2024-06-22 21:40:27.351 Debug Server: http/1.1 Response 200 to ::1. Time: 1124ms. GET http://localhost:7000/Bangumi/OAuth?user=省略&code=省略
2024-06-22 21:40:30.933 Debug Server: http/1.1 GET http://192.168.31.240:7000/emby/System/Logs/embyserver.txt?Sanitize=true&api_key=x_secret2_x. Source Ip: host1, UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
```

**Comment by ll2963336** [comment]
感谢大佬。这个版本结果上看也是不行，日志上看卡在授权相关上面

> bangumiLite版本号：`1.6.0.0`

+ 执行已下操作&弹出信息
1. 授权后跳转的页面 (url:`http://localhost:7000/Bangumi/OAuth?user=省略&code=省略`)，报`Failed to handle bangumi callback: Unauthorized: need Login`
2. 刷新授权页面，报`{"error":"invalid_grant","error_description":"Authorization code doesn't exist or is invalid for the client"}`

+ 日志如下（user & code人为省略，上同）
```
2024-06-22 21:40:24.272 Debug Server: http/1.1 GET http://localhost:7000/emby/Bangumi/Redirect?prefix=http://localhost:7000&user=省略. Source Ip: ::1, UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0
2024-06-22 21:40:24.273 Debug Server: http/1.1 Response 302 to ::1. Time: 1ms. GET http://localhost:7000/emby/Bangumi/Redirect?prefix=http://localhost:7000&user=省略
2024-06-22 21:40:26.227 Debug Server: http/1.1 GET http://localhost:7000/Bangumi/OAuth?user=省略&code=省略. Source Ip: ::1, UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0
2024-06-22 21:40:26.228 Info HttpClient: POST https://bgm.tv/oauth/access_token
2024-06-22 21:40:26.749 Info HttpClient: GET https://api.bgm.tv/v0/me
2024-06-22 21:40:27.349 Error App: Unauthorized: need Login
2024-06-22 21:40:27.351 Error Server: Error processing request
	*** Error Report ***
	Version: 4.9.0.25
	Command line: C:\Users\nasnas\AppData\Roaming\Emby-Server\system\EmbyServer.dll -noautorunwebapp
	Operating system: Microsoft Windows 10.0.19044
	OS/Process: x64/x64
	Framework: .NET 8.0.5
	Runtime: C:/Users/nasnas/AppData/Roaming/Emby-Server/system/System.Private.CoreLib.dll
	Processor count: 8
	Data path: C:\Users\nasnas\AppData\Roaming\Emby-Server\programdata
	Application path: C:\Users\nasnas\AppData\Roaming\Emby-Server\system
	System.InvalidOperationException: System.InvalidOperationException: StatusCode cannot be set because the response has already started.
	   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ThrowResponseAlreadyStartedException(String value)
	   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.set_StatusCode(Int32 value)
	   at Emby.Server.Implementations.Services.ResponseHelper.WriteToResponse(HttpListenerHost httpListenerHost, IResponse response, IRequest request, IStreamHelper streamHelper, Object result, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IServerApplicationHost appHost, IRequest httpReq, IResponse httpRes, IStreamHelper streamHelper, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
	Source: Microsoft.AspNetCore.Server.Kestrel.Core
	TargetSite: Void ThrowResponseAlreadyStartedException(System.String)
	
2024-06-22 21:40:27.351 Debug Server: http/1.1 Response 200 to ::1. Time: 1124ms. GET http://localhost:7000/Bangumi/OAuth?user=省略&code=省略
2024-06-22 21:40:30.933 Debug Server: http/1.1 GET http://192.168.31.240:7000/emby/System/Logs/embyserver.txt?Sanitize=true&api_key=x_secret2_x. Source Ip: host1, UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
```

**Comment by salomejou** [comment]
jellyfin也不能显示里番合集，都是一集一集的
