### ISSUE TITLE
刮削未找到符合您搜索条件的项目，大家的刮削结果如何

### ISSUE THREAD

**Issue by chuyinluotian01** [kookxiang/jellyfin-plugin-bangumi#140]
![1b601dfe6c8bba7f49cccbddfa1ec513](https://github.com/user-attachments/assets/0e40746a-3bdb-4fb4-b6a0-f0e051a5dffb)
![6f69739065a6fdc717fe8bbe915b0760](https://github.com/user-attachments/assets/73b6d1b7-290f-4fd4-bb9e-5b85a8b8603f)
![aed5a1b8687ebda46558d99946673585](https://github.com/user-attachments/assets/d1c1a085-7992-42a0-b195-80377c74264f)
改hosts，开了旁路由，还是搜索不到结果

**Comment by kookxiang** [comment]
发一下搜索的日志看看

**Comment by chuyinluotian01** [comment]
Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
Operating system: Linux version 4.4.302+ (root@build7) (gcc version 12.2.0 (GCC) ) #64561 SMP Fri May 19 01:32:50 CST 2023
OS/Process: x64/x64
Framework: .NET 8.0.6
Runtime: system/System.Private.CoreLib.dll
Processor count: 8
Data path: /config
Application path: /system
MediaBrowser.Model.Net.HttpException: MediaBrowser.Model.Net.HttpException: Cancelling connection to https://api.bgm.tv/search/subject/%E9%9B%AA%E4%B9%8B%E5%B0%91%E5%A5%B3?responseGroup=large&type=2 due to a previous timeout.
at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsync(HttpRequestOptions options, String httpMethod)
at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest(String method, HttpRequestOptions options)
at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest[T](String url, String accessToken, CancellationToken token)
at Jellyfin.Plugin.Bangumi.BangumiApi.SearchSubject(String keyword, Nullable`1 type, CancellationToken token)
at Jellyfin.Plugin.Bangumi.ExternalIdProvider.SeriesProvider.GetMetadata(SeriesInfo info, CancellationToken token)
at Emby.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, LibraryOptions libraryOptions, String logName, TIdType id, IRemoteMetadataProvider`2[] providers, MetadataRefreshOptions options, CancellationToken cancellationToken)
Source: Emby.Server.Implementations
TargetSite: Void MoveNext()
2024-07-15 09:48:12.884 Info HttpClient: GET https://api.themoviedb.org/3/tv/72540?api_key=x_secret3_x&append_to_response=alternative_titles,reviews,credits,images,keywords,external_ids,videos,content_ratings,episode_groups
2024-07-15 09:48:12.884 Error ProviderManager: MovieDbSeriesImageProvider failed in GetImageInfos for type Series
*** Error Report ***
Version: 4.9.0.25
Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
Operating system: Linux version 4.4.302+ (root@build7) (gcc version 12.2.0 (GCC) ) #64561 SMP Fri May 19 01:32:50 CST 2023
OS/Process: x64/x64
Framework: .NET 8.0.6
Runtime: system/System.Private.CoreLib.dll
Processor count: 8
Data path: /config
Application path: /system
MediaBrowser.Model.Net.HttpException: MediaBrowser.Model.Net.HttpException: Cancelling connection to https://api.themoviedb.org/3/tv/72540?api_key=x_secret3_x&append_to_response=alternative_titles,reviews,credits,images,keywords,external_ids,videos,content_ratings,episode_groups due to a previous timeout.
at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsync(HttpRequestOptions options, String httpMethod)
at MovieDb.MovieDbProviderBase.GetMovieDbResponse(HttpRequestOptions options)
at MovieDb.MovieDbSeriesProvider.FetchMainResult(String id, String language, CancellationToken cancellationToken)
at MovieDb.MovieDbSeriesProvider.DownloadSeriesInfo(String id, String preferredMetadataLanguage, CancellationToken cancellationToken)
at MovieDb.MovieDbSeriesImageProvider.FetchImages(BaseItem item, IJsonSerializer jsonSerializer, CancellationToken cancellationToken)
at MovieDb.MovieDbSeriesImageProvider.GetImages(RemoteImageFetchOptions options, CancellationToken cancellationToken)
at Emby.Providers.Manager.ProviderManager.GetImages(RemoteImageFetchOptions options, CancellationToken cancellationToken, IRemoteImageProvider provider, Int32 providerIndex)
Source: Emby.Server.Implementations
TargetSite: Void MoveNext()

**Comment by chuyinluotian01** [comment]
已解决
