### ISSUE TITLE
【刮削报错】名侦探柯南：天空的遇难船

### ISSUE THREAD

**Issue by Archer-Tatsu** [kookxiang/jellyfin-plugin-bangumi#145]
bgm连接：https://bgm.tv/subject/3628
刮削时会报如下的错误，之后fallback到其他数据源的数据。
目前看是稳定复现的。其他剧场版暂时没发现这个问题。

```
[2024-07-28 17:58:57.369 +08:00] [ERR] [66] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "Bangumi"
System.InvalidOperationException: The requested operation requires an element of type 'String', but the target element has type 'Array'.
   at System.Text.Json.ThrowHelper.ThrowJsonElementWrongTypeException(JsonTokenType expectedType, JsonTokenType actualType)
   at System.Text.Json.JsonDocument.GetString(Int32 index, JsonTokenType expectedType)
   at Jellyfin.Plugin.Bangumi.Model.InfoBox.GetString(String key)
   at Jellyfin.Plugin.Bangumi.Providers.MovieProvider.GetMetadata(MovieInfo info, CancellationToken token)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```

**Comment by Archer-Tatsu** [comment]
大佬光速修复！刚试了下ci最新版问题没了！感谢！我先关了
