### ISSUE TITLE
在 Jellyfin 10.10.0版本上安装 Bangumi 1.6.2.0 后，Jellyfin无法启动

### ISSUE THREAD

**Issue by HatsuneMona** [kookxiang/jellyfin-plugin-bangumi#155]
如题。
使用的是官方Docker版本的Jellyfin安装Bangumi 1.6.2.0后，Jellyfin无法正常启动。

Jellyfin版本：docker pull jellyfin/jellyfin:2024093005

Bangumi版本：1.6.2.0

错误日志：
```log
[21:23:21] [INF] [1] Main: Jellyfin version: 10.10.0
[21:23:21] [INF] [1] Main: Arguments: ["/jellyfin/jellyfin.dll"]
[21:23:21] [INF] [1] Main: Operating system: Debian GNU/Linux 12 (bookworm)
[21:23:21] [INF] [1] Main: Architecture: X64
[21:23:21] [INF] [1] Main: 64-Bit Process: True
[21:23:21] [INF] [1] Main: User Interactive: True
[21:23:21] [INF] [1] Main: Processor count: 3
[21:23:21] [INF] [1] Main: Program data path: /config
[21:23:21] [INF] [1] Main: Log directory path: /config/log
[21:23:21] [INF] [1] Main: Config directory path: /config/config
[21:23:21] [INF] [1] Main: Cache path: /cache
[21:23:21] [INF] [1] Main: Temp directory path: /tmp/jellyfin
[21:23:21] [INF] [1] Main: Web resources path: /jellyfin/jellyfin-web
[21:23:21] [INF] [1] Main: Application directory: /jellyfin/
[21:23:21] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /cache
[21:23:21] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[21:23:21] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly AnitomySharp, Version=0.2.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Bangumi_1.6.2.0/AnitomySharp.dll
[21:23:21] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Fastenshtein, Version=1.0.0.8, Culture=neutral, PublicKeyToken=null from /config/plugins/Bangumi_1.6.2.0/Fastenshtein.dll
[21:23:21] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Bangumi, Version=1.6.2.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Bangumi_1.6.2.0/Jellyfin.Plugin.Bangumi.dll
**[21:23:28] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Bangumi 1.6.2.0**
[21:23:29] [ERR] [1] Main: Kestrel failed to start! This is most likely due to an invalid address or port bind - correct your bind configuration in network.xml and try again
[21:23:29] [FTL] [1] Main: Error while starting server
System.MissingMethodException: Method not found: 'System.Collections.Generic.List`1<MediaBrowser.Controller.Entities.UserItemData> MediaBrowser.Controller.Library.IUserDataManager.GetAllUserData(System.Guid)'.
   at Jellyfin.Plugin.Bangumi.PlaybackScrobbler.GetPlaybackHistory(Guid userId)
   at Jellyfin.Plugin.Bangumi.PlaybackScrobbler..ctor(IUserManager userManager, IUserDataManager userDataManager, ILocalizationManager localizationManager, OAuthStore store, BangumiApi api, ILogger`1 log)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
[21:23:29] [INF] [1] Main: Running query planner optimizations in the database... This might take a while
```

**Comment by kookxiang** [comment]
10.10 目前还没做兼容，我研究下

**Comment by HatsuneMona** [comment]
收到，感谢大佬！

**Comment by kookxiang** [comment]
https://github.com/kookxiang/jellyfin-plugin-bangumi/actions/runs/11194177935
可以试试看这个版本能不能用

**Comment by HatsuneMona** [comment]
谢谢，经过测试，最新的版本经过测试已经可以使用了！
