### ISSUE TITLE
升级Jellfyin 10.10之后，本插件会导致Jellyfin无法启动

### ISSUE THREAD

**Issue by Izumiko** [kookxiang/jellyfin-plugin-bangumi#169]
Docker升级Jellfyin到10.10后，发现无法访问，检查日志并删除jellyfin-plugin-bangumi的目录后成功启动。日志如下：

```log
[06:23:13] [INF] [1] Main: Environment Variables: ["[JELLYFIN_FFMPEG, /usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_DATA_DIR, /config]", "[JELLYFIN_CONFIG_DIR, /config/config]", "[JELLYFIN_PublishedServerUrl, http://media.987655.xyz]", "[JELLYFIN_CACHE_DIR, /cache]", "[JELLYFIN_WEB_DIR, /jellyfin/jellyfin-web]", "[JELLYFIN_LOG_DIR, /config/log]"]
[06:23:13] [INF] [1] Main: Arguments: ["/jellyfin/jellyfin.dll"]
[06:23:13] [INF] [1] Main: Operating system: Debian GNU/Linux 12 (bookworm)
[06:23:13] [INF] [1] Main: Architecture: X64
[06:23:13] [INF] [1] Main: 64-Bit Process: True
[06:23:13] [INF] [1] Main: User Interactive: True
[06:23:13] [INF] [1] Main: Processor count: 2
[06:23:13] [INF] [1] Main: Program data path: /config
[06:23:13] [INF] [1] Main: Log directory path: /config/log
[06:23:13] [INF] [1] Main: Config directory path: /config/config
[06:23:13] [INF] [1] Main: Cache path: /cache
[06:23:13] [INF] [1] Main: Temp directory path: /tmp/jellyfin
[06:23:13] [INF] [1] Main: Web resources path: /jellyfin/jellyfin-web
[06:23:13] [INF] [1] Main: Application directory: /jellyfin/
[06:23:13] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /cache
[06:23:13] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[06:23:13] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly jellyfin-ani-sync, Version=3.4.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Ani-Sync_3.4.0.0/jellyfin-ani-sync.dll
[06:23:13] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly AnitomySharp, Version=0.2.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Bangumi_1.6.2.0/AnitomySharp.dll
[06:23:13] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Fastenshtein, Version=1.0.0.8, Culture=neutral, PublicKeyToken=null from /config/plugins/Bangumi_1.6.2.0/Fastenshtein.dll
[06:23:13] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Bangumi, Version=1.6.2.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Bangumi_1.6.2.0/Jellyfin.Plugin.Bangumi.dll
[06:23:13] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Danmu, Version=2.0.9.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Danmu_2.0.9.0/Jellyfin.Plugin.Danmu.dll
[06:23:13] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly InfuseSync, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/InfuseSync_1.5.0.0/InfuseSync.dll
[06:23:13] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly MetaTube, Version=2024.612.210.0, Culture=neutral, PublicKeyToken=null from /config/plugins/MetaTube_2024.612.210.0/MetaTube.dll
[06:23:13] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN subnets: ["::1/128", "fe80::/10", "fc00::/7", "127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[06:23:13] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions: []
[06:23:13] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Used LAN subnets: ["::1/128", "fe80::/10", "fc00::/7", "127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[06:23:13] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered interface addresses: ["127.0.0.1", "172.17.15.152", "192.168.222.3", "172.21.0.1", "172.18.0.1", "172.22.0.1", "172.23.0.1", "172.20.0.1", "::1", "fe80::a8fd:d2ff:fef3:56b2%2", "fe80::ecbe:13ff:fe55:8ed0%3", "fe80::42:92ff:fece:fa95%4", "fe80::42:8bff:feaa:5a73%5", "fe80::42:b2ff:fe09:2c03%6", "fe80::42:29ff:febe:559c%7", "fe80::42:6ff:fe11:d346%8"]
[06:23:13] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Bind Addresses ["::"]
[06:23:13] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Remote IP filter is Allowlist
[06:23:13] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered subnets: []
[06:23:17] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Ani-Sync 3.4.0.0
[06:23:17] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Bangumi 1.6.2.0
[06:23:17] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Danmu 2.0.9.0
[06:23:17] [INF] [1] InfuseSync.Plugin: InfuseSync is starting.
[06:23:17] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: InfuseSync 1.5.0.0
[06:23:17] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: MetaTube 2024.612.210.0
[06:23:17] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: TMDb 10.10.0.0
[06:23:17] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Studio Images 10.10.0.0
[06:23:17] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: OMDb 10.10.0.0
[06:23:17] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: MusicBrainz 10.10.0.0
[06:23:17] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AudioDB 10.10.0.0
[06:23:17] [ERR] [1] Main: Kestrel failed to start! This is most likely due to an invalid address or port bind - correct your bind configuration in network.xml and try again
[06:23:17] [FTL] [1] Main: Error while starting server
System.MissingMethodException: Method not found: 'System.Collections.Generic.List`1<MediaBrowser.Controller.Entities.UserItemData> MediaBrowser.Controller.Library.IUserDataManager.GetAllUserData(System.Guid)'.
   at Jellyfin.Plugin.Bangumi.PlaybackScrobbler.GetPlaybackHistory(Guid userId)
   at Jellyfin.Plugin.Bangumi.PlaybackScrobbler..ctor(IUserManager userManager, IUserDataManager userDataManager, ILocalizationManager localizationManager, OAuthStore store, BangumiApi api, ILogger`1 log)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
[06:23:17] [INF] [1] Main: Running query planner optimizations in the database... This might take a while
[06:23:17] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing CoreAppHost
[06:23:17] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing MusicBrainzArtistProvider
[06:23:17] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing MusicBrainzAlbumProvider
[06:23:17] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing PluginManager
```

**Comment by kookxiang** [comment]
https://github.com/kookxiang/jellyfin-plugin-bangumi/actions/workflows/jellyfin.yml?query=branch%3Amaster
先下载 master 版本，这两天等离线数据库弄完了发一版
