### ISSUE TITLE
在 Jellyfin 10.9.9版本上更新插件1.7.0.0 后，插件状态变成NotSupported

### ISSUE THREAD

**Issue by ymdm2** [kookxiang/jellyfin-plugin-bangumi#171]
如题，在 Jellyfin 10.9.9版本上更新插件1.7.0.0 后，插件状态变成NotSupported，媒体库元数据里没有bangumi的选项
部分Jellyfin的日志：
```
[2024-10-31 00:06:11.673 +08:00] [INF] [1] Main: Jellyfin version: "10.9.9"
[2024-10-31 00:06:11.690 +08:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, D:\Jellyfin\Server data\log]"]
[2024-10-31 00:06:11.693 +08:00] [INF] [1] Main: Arguments: ["D:\Jellyfin\Server\jellyfin.dll", "--datadir", "D:\Jellyfin\Server data"]
[2024-10-31 00:06:11.696 +08:00] [INF] [1] Main: Operating system: "Microsoft Windows 10.0.22631"
[2024-10-31 00:06:11.697 +08:00] [INF] [1] Main: Architecture: X64
[2024-10-31 00:06:11.699 +08:00] [INF] [1] Main: 64-Bit Process: True
[2024-10-31 00:06:11.700 +08:00] [INF] [1] Main: User Interactive: True
[2024-10-31 00:06:11.700 +08:00] [INF] [1] Main: Processor count: 16
[2024-10-31 00:06:11.701 +08:00] [INF] [1] Main: Program data path: "D:\Jellyfin\Server data"
[2024-10-31 00:06:11.702 +08:00] [INF] [1] Main: Log directory path: "D:\Jellyfin\Server data\log"
[2024-10-31 00:06:11.704 +08:00] [INF] [1] Main: Config directory path: "D:\Jellyfin\Server data\config"
[2024-10-31 00:06:11.704 +08:00] [INF] [1] Main: Cache path: "D:\Jellyfin\Server data\cache"
[2024-10-31 00:06:11.705 +08:00] [INF] [1] Main: Web resources path: "D:\Jellyfin\Server\jellyfin-web"
[2024-10-31 00:06:11.706 +08:00] [INF] [1] Main: Application directory: "D:\Jellyfin\Server\"
[2024-10-31 00:06:13.053 +08:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "D:\Jellyfin\Server data\cache"
[2024-10-31 00:06:14.090 +08:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2024-10-31 00:06:14.750 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "AnitomySharp, Version=0.2.0.0, Culture=neutral, PublicKeyToken=null" from "D:\Jellyfin\Server data\plugins\Bangumi_1.6.2.0\AnitomySharp.dll"
[2024-10-31 00:06:14.752 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Fastenshtein, Version=1.0.0.8, Culture=neutral, PublicKeyToken=null" from "D:\Jellyfin\Server data\plugins\Bangumi_1.6.2.0\Fastenshtein.dll"
[2024-10-31 00:06:14.835 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Bangumi, Version=1.6.2.0, Culture=neutral, PublicKeyToken=null" from "D:\Jellyfin\Server data\plugins\Bangumi_1.6.2.0\Jellyfin.Plugin.Bangumi.dll"
[2024-10-31 00:06:14.837 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin "1.7.0.0" of "Bangumi" 
[2024-10-31 00:06:15.502 +08:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-10-31 00:06:15.504 +08:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions: []
[2024-10-31 00:06:15.506 +08:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Used LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-10-31 00:06:15.508 +08:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered interface addresses: ["192.168.31.169", "127.0.0.1"]
[2024-10-31 00:06:15.510 +08:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Bind Addresses ["0.0.0.0"]
[2024-10-31 00:06:15.512 +08:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Remote IP filter is "Allowlist"
[2024-10-31 00:06:15.513 +08:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered subnets: []
[2024-10-31 00:06:19.409 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Bangumi" "1.6.2.0"
[2024-10-31 00:06:19.411 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TMDb" "10.9.9.0"
[2024-10-31 00:06:19.412 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Studio Images" "10.9.9.0"
[2024-10-31 00:06:19.414 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "OMDb" "10.9.9.0"
[2024-10-31 00:06:19.462 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "MusicBrainz" "10.9.9.0"
[2024-10-31 00:06:19.464 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AudioDB" "10.9.9.0"
[2024-10-31 00:06:19.673 +08:00] [INF] [1] Main: Kestrel is listening on "0.0.0.0"
[2024-10-31 00:06:20.621 +08:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[2024-10-31 00:06:20.622 +08:00] [INF] [7] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "D:\动画\新番"
[2024-10-31 00:06:20.622 +08:00] [INF] [9] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "D:\动画\往季番"
[2024-10-31 00:06:20.622 +08:00] [INF] [14] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "D:\动画\动画电影"
[2024-10-31 00:06:20.651 +08:00] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "生成时间轴缩略图" set to fire at 2024-10-31 03:00:00.000 +08:00, which is 02:53:39.3484550 from now.
[2024-10-31 00:06:20.674 +08:00] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "提取章节图片" set to fire at 2024-10-31 02:00:00.000 +08:00, which is 01:53:39.3250678 from now.
[2024-10-31 00:06:21.000 +08:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version "6.0.1"
[2024-10-31 00:06:21.188 +08:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "decoders": ["libdav1d", "av1", "av1_cuvid", "av1_qsv", "h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8", "libvpx", "vp8_cuvid", "vp8_qsv", "vp9", "libvpx-vp9", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "dca", "flac", "mp3", "truehd"]
[2024-10-31 00:06:21.340 +08:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "encoders": ["libsvtav1", "av1_nvenc", "av1_qsv", "av1_amf", "libx264", "h264_amf", "h264_nvenc", "h264_qsv", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "mjpeg_qsv", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "libfdk_aac", "ac3", "alac", "dca", "flac", "libmp3lame", "libopus", "truehd", "libvorbis", "srt"]
[2024-10-31 00:06:21.500 +08:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available filters: ["deinterlace_qsv", "hwupload_cuda", "overlay_opencl", "overlay_qsv", "overlay_cuda", "scale_cuda", "scale_opencl", "scale_qsv", "tonemap_cuda", "tonemap_opencl", "vpp_qsv", "yadif_cuda", "zscale", "alphasrc"]
[2024-10-31 00:06:22.235 +08:00] [WRN] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Filter: "overlay_vaapi" with option "Action to take when encountering EOF from secondary input" is not available
[2024-10-31 00:06:22.369 +08:00] [WRN] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Filter: "overlay_vulkan" with option "Action to take when encountering EOF from secondary input" is not available
[2024-10-31 00:06:22.519 +08:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["cuda", "dxva2", "qsv", "d3d11va", "opencl"]
[2024-10-31 00:06:22.928 +08:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: "ffmpeg"
[2024-10-31 00:06:22.937 +08:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: ServerId: "f3538b3b8ae545ae886e5fff3ed7d052"
[2024-10-31 00:06:22.939 +08:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Core startup complete
[2024-10-31 00:06:22.940 +08:00] [INF] [1] Main: Startup complete 0:00:12.6030737
[2024-10-31 00:06:23.698 +08:00] [INF] [14] Emby.Server.Implementations.ScheduledTasks.TaskManager: "清理合集和播放列表" Completed after 0 minute(s) and 0 seconds
[2024-10-31 00:07:08.264 +08:00] [INF] [17] Emby.Server.Implementations.Updates.InstallationManager: Plugin "updated": "Bangumi" "1.7.0.0"
[2024-10-31 00:07:08.446 +08:00] [INF] [17] Emby.Server.Implementations.ApplicationHost: App needs to be restarted.
[2024-10-31 00:07:08.449 +08:00] [INF] [17] Emby.Server.Implementations.ScheduledTasks.TaskManager: "更新插件" Completed after 0 minute(s) and 44 seconds
[2024-10-31 00:07:20.651 +08:00] [INF] [17] Emby.Server.Implementations.ScheduledTasks.TaskManager: "OAuth 登录令牌刷新" Completed after 0 minute(s) and 0 seconds
[2024-10-31 00:09:23.924 +08:00] [INF] [17] Emby.Server.Implementations.IO.LibraryMonitor: "新番" ("D:\动画\新番") will be refreshed.
[2024-10-31 00:09:25.883 +08:00] [INF] [20] Jellyfin.Plugin.Bangumi.Providers.SeriesProvider: Searching "海贼王-Fan Letter" in bgm.tv
[2024-10-31 00:10:25.829 +08:00] [INF] [17] Emby.Server.Implementations.IO.LibraryMonitor: "海贼王-Fan Letter" ("D:\动画\新番\海贼王-Fan Letter") will be refreshed.
[2024-10-31 00:10:25.831 +08:00] [INF] [17] Emby.Server.Implementations.IO.LibraryMonitor: "[one_piece" ("D:\动画\新番\海贼王-Fan Letter\[OPFansMaplesnow][one_piece][2024][Special][Fan Letter][chs][x264_aac][1080p].mp4") will be refreshed.
[2024-10-31 00:10:25.832 +08:00] [INF] [20] Jellyfin.Plugin.Bangumi.Providers.SeriesProvider: Searching "海贼王-Fan Letter" in bgm.tv
[2024-10-31 00:10:29.478 +08:00] [INF] [20] MediaBrowser.Providers.TV.SeriesMetadataService: Creating Season "未知季" entry for "海贼王-Fan Letter"
[2024-10-31 00:10:29.504 +08:00] [INF] [30] MediaBrowser.Providers.TV.SeriesMetadataService: Removing virtual season null in series "海贼王-Fan Letter"
[2024-10-31 00:10:29.508 +08:00] [INF] [30] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "未知季", Path: "", Id: 84c61c33-9742-0c67-32ba-d9b2cae044f2
[2024-10-31 00:10:29.513 +08:00] [INF] [30] MediaBrowser.Providers.TV.SeriesMetadataService: Creating Season "未知季" entry for "海贼王-Fan Letter"
[2024-10-31 00:10:29.548 +08:00] [INF] [30] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"D:\动画\新番\海贼王-Fan Letter\[OPFansMaplesnow][one_piece][2024][Special][Fan Letter][chs][x264_aac][1080p].mp4\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-10-31 00:10:29.807 +08:00] [ERR] [20] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in "Probe Provider"
MediaBrowser.Common.FfmpegException: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2024-10-31 00:10:30.107 +08:00] [INF] [20] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: metadata for "[OPFansMaplesnow][one_piece][2024][Special][Fan Letter][chs][x264_aac][1080p].mp4": null
[2024-10-31 00:10:30.118 +08:00] [INF] [20] MediaBrowser.Providers.TV.SeriesMetadataService: Removing virtual season null in series "海贼王-Fan Letter"
[2024-10-31 00:10:30.120 +08:00] [INF] [20] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Season", Name: "未知季", Path: "", Id: 84c61c33-9742-0c67-32ba-d9b2cae044f2
[2024-10-31 00:10:30.123 +08:00] [INF] [20] MediaBrowser.Providers.TV.SeriesMetadataService: Creating Season "第 1 季" entry for "海贼王-Fan Letter"
[2024-10-31 00:10:30.139 +08:00] [INF] [20] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"D:\动画\新番\海贼王-Fan Letter\[OPFansMaplesnow][one_piece][2024][Special][Fan Letter][chs][x264_aac][1080p].mp4\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-10-31 00:10:30.293 +08:00] [ERR] [30] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in "Probe Provider"
MediaBrowser.Common.FfmpegException: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2024-10-31 00:34:09.448 +08:00] [INF] [10] Emby.Server.Implementations.IO.LibraryMonitor: "[one_piece" ("D:\动画\新番\海贼王-Fan Letter\[OPFansMaplesnow][one_piece][2024][Special][Fan Letter][chs][x264_aac][1080p].mp4") will be refreshed.
[2024-10-31 00:34:09.456 +08:00] [INF] [32] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"D:\动画\新番\海贼王-Fan Letter\[OPFansMaplesnow][one_piece][2024][Special][Fan Letter][chs][x264_aac][1080p].mp4\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-10-31 11:51:01.922 +08:00] [INF] [1] Main: Jellyfin version: "10.9.9"
[2024-10-31 11:51:01.935 +08:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, D:\Jellyfin\Server data\log]"]
[2024-10-31 11:51:01.938 +08:00] [INF] [1] Main: Arguments: ["D:\Jellyfin\Server\jellyfin.dll", "--datadir", "D:\Jellyfin\Server data"]
[2024-10-31 11:51:01.940 +08:00] [INF] [1] Main: Operating system: "Microsoft Windows 10.0.22631"
[2024-10-31 11:51:01.941 +08:00] [INF] [1] Main: Architecture: X64
[2024-10-31 11:51:01.942 +08:00] [INF] [1] Main: 64-Bit Process: True
[2024-10-31 11:51:01.943 +08:00] [INF] [1] Main: User Interactive: True
[2024-10-31 11:51:01.945 +08:00] [INF] [1] Main: Processor count: 16
[2024-10-31 11:51:01.946 +08:00] [INF] [1] Main: Program data path: "D:\Jellyfin\Server data"
[2024-10-31 11:51:01.946 +08:00] [INF] [1] Main: Log directory path: "D:\Jellyfin\Server data\log"
[2024-10-31 11:51:01.947 +08:00] [INF] [1] Main: Config directory path: "D:\Jellyfin\Server data\config"
[2024-10-31 11:51:01.948 +08:00] [INF] [1] Main: Cache path: "D:\Jellyfin\Server data\cache"
[2024-10-31 11:51:01.949 +08:00] [INF] [1] Main: Web resources path: "D:\Jellyfin\Server\jellyfin-web"
[2024-10-31 11:51:01.950 +08:00] [INF] [1] Main: Application directory: "D:\Jellyfin\Server\"
[2024-10-31 11:51:03.230 +08:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "D:\Jellyfin\Server data\cache"
[2024-10-31 11:51:04.236 +08:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2024-10-31 11:51:05.018 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "AnitomySharp, Version=0.5.1.0, Culture=neutral, PublicKeyToken=null" from "D:\Jellyfin\Server data\plugins\Bangumi_1.7.0.0\AnitomySharp.dll"
[2024-10-31 11:51:05.020 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Fastenshtein, Version=1.0.10.0, Culture=neutral, PublicKeyToken=null" from "D:\Jellyfin\Server data\plugins\Bangumi_1.7.0.0\Fastenshtein.dll"
[2024-10-31 11:51:05.022 +08:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "FuzzySharp, Version=1.0.4.0, Culture=neutral, PublicKeyToken=null" from "D:\Jellyfin\Server data\plugins\Bangumi_1.7.0.0\FuzzySharp.dll"
[2024-10-31 11:51:05.108 +08:00] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly "D:\Jellyfin\Server data\plugins\Bangumi_1.7.0.0\Jellyfin.Plugin.Bangumi.dll". This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'MediaBrowser.Common, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Controller, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Model, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Model, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Model, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Controller, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Controller, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Controller, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Controller, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Controller, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Controller, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Controller, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Controller, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Controller, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Controller, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Controller, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Controller, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Controller, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Controller, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Controller, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Controller, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Controller, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Controller, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Controller, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Controller, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Model, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Controller, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Controller, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Model, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Model, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Controller, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Model, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Controller, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Model, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Controller, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Controller, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Model, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Controller, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Controller, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Model, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Controller, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Model, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Controller, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Controller, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Model, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Model, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Controller, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Controller, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
Could not load file or assembly 'MediaBrowser.Controller, Version=10.10.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
```

**Comment by Inuyasha-cxk** [comment]
我10.9.6也出现不支持，升级到10.10.0之后插件正常加载了，Windows环境

**Comment by kookxiang** [comment]
可以试试 actions 里面打的版本，我把 sdk 版本降回去了
