### ISSUE TITLE
v1.7.0 离线数据库更新失败

### ISSUE THREAD

**Issue by jones-187** [kookxiang/jellyfin-plugin-bangumi#174]
1、版本：
jellyfin: v10.10.0
jellyfin-plugin-bangumi: v1.7.0

2、现象：

- 计划任务提示更新离线数据库失败。断网查询用名称和bangumiId都查不到

![image](https://github.com/user-attachments/assets/672b3f90-8c99-4577-bf4b-33ef9630724d)

- 插件配置里又有相关信息：

![image](https://github.com/user-attachments/assets/897318a3-792a-4396-bc72-d96aac73773f)

- 每更新失败一次，数据库文件夹就会增大一些：
![image](https://github.com/user-attachments/assets/77308dfa-bc94-4eb8-a448-0de05654e85e)

3、日志
```

[2024-11-02 12:17:57.687 +08:00] [INF] [23] Jellyfin.Plugin.Bangumi.ScheduledTask.ArchiveDownloadTask: download bangumi archive data from "https://github.com/bangumi/Archive/releases/download/archive/dump-2024-10-29.210231Z.zip"
[2024-11-02 12:18:07.773 +08:00] [INF] [16] Jellyfin.Plugin.Bangumi.ScheduledTask.ArchiveDownloadTask: download complete, total size: 311289591
[2024-11-02 12:18:07.777 +08:00] [INF] [16] Jellyfin.Plugin.Bangumi.ScheduledTask.ArchiveDownloadTask: decompressing "character.jsonlines" to "temp/iv2wohkl.is3"
[2024-11-02 12:18:08.136 +08:00] [INF] [16] Jellyfin.Plugin.Bangumi.ScheduledTask.ArchiveDownloadTask: generating index for "temp/iv2wohkl.is3"
[2024-11-02 12:18:08.960 +08:00] [INF] [35] Jellyfin.Plugin.Bangumi.ScheduledTask.ArchiveDownloadTask: replacing "character.jsonlines" and index files with "temp/iv2wohkl.is3"
[2024-11-02 12:18:08.971 +08:00] [INF] [16] Jellyfin.Plugin.Bangumi.ScheduledTask.ArchiveDownloadTask: decompressing "subject.jsonlines" to "temp/0kyqy5bg.llc"
[2024-11-02 12:18:10.945 +08:00] [INF] [25] Jellyfin.Plugin.Bangumi.ScheduledTask.ArchiveDownloadTask: generating index for "temp/0kyqy5bg.llc"
[2024-11-02 12:18:14.780 +08:00] [INF] [35] Jellyfin.Plugin.Bangumi.ScheduledTask.ArchiveDownloadTask: replacing "subject.jsonlines" and index files with "temp/0kyqy5bg.llc"
[2024-11-02 12:18:14.786 +08:00] [INF] [23] Jellyfin.Plugin.Bangumi.ScheduledTask.ArchiveDownloadTask: decompressing "episode.jsonlines" to "temp/sqiw4hju.l3w"
[2024-11-02 12:18:15.343 +08:00] [INF] [23] Jellyfin.Plugin.Bangumi.ScheduledTask.ArchiveDownloadTask: generating index for "temp/sqiw4hju.l3w"
[2024-11-02 12:18:17.535 +08:00] [INF] [35] Jellyfin.Plugin.Bangumi.ScheduledTask.ArchiveDownloadTask: replacing "episode.jsonlines" and index files with "temp/sqiw4hju.l3w"
[2024-11-02 12:18:17.542 +08:00] [INF] [31] Jellyfin.Plugin.Bangumi.ScheduledTask.ArchiveDownloadTask: decompressing "person.jsonlines" to "temp/dsqaaxd2.pvr"
[2024-11-02 12:18:17.689 +08:00] [INF] [25] Jellyfin.Plugin.Bangumi.ScheduledTask.ArchiveDownloadTask: generating index for "temp/dsqaaxd2.pvr"
[2024-11-02 12:18:18.034 +08:00] [INF] [23] Jellyfin.Plugin.Bangumi.ScheduledTask.ArchiveDownloadTask: replacing "person.jsonlines" and index files with "temp/dsqaaxd2.pvr"
[2024-11-02 12:18:20.978 +08:00] [ERR] [25] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
System.IO.IOException: The process cannot access the file because it is being used by another process.
   at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at Jellyfin.Plugin.Bangumi.Archive.Relation.SubjectEpisodeRelation.Save()
   at Jellyfin.Plugin.Bangumi.Archive.Relation.SubjectEpisodeRelation.Save()
   at Jellyfin.Plugin.Bangumi.Archive.Relation.SubjectEpisodeRelation.Save()
   at Jellyfin.Plugin.Bangumi.Archive.Relation.SubjectEpisodeRelation.GenerateIndex(CancellationToken token)
   at Jellyfin.Plugin.Bangumi.ScheduledTask.ArchiveDownloadTask.ExecuteAsync(IProgress`1 progress, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.ScheduledTask.ArchiveDownloadTask.ExecuteAsync(IProgress`1 progress, CancellationToken token)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2024-11-02 12:18:20.985 +08:00] [INF] [25] Emby.Server.Implementations.ScheduledTasks.TaskManager: "离线数据库更新" Failed after 0 minute(s) and 23 seconds
``` 

断网测试，好像没走离线数据库
```

[2024-11-02 12:21:16.528 +08:00] [INF] [29] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-11-02 12:22:16.524 +08:00] [INF] [14] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-11-02 12:23:34.525 +08:00] [INF] [14] Jellyfin.Plugin.Bangumi.BangumiApi: request api without cache: https://api.bgm.tv/v0/subjects/467461
[2024-11-02 12:23:34.534 +08:00] [ERR] [14] MediaBrowser.Providers.Manager.ProviderManager: Provider "Bangumi" failed to retrieve search results
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Unable to read data from the transport connection: 远程主机强迫关闭了一个现有的连接。.
 ---> System.Net.Sockets.SocketException (10054): 远程主机强迫关闭了一个现有的连接。
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendWithOutCache(HttpRequestMessage request, String accessToken, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.<>c__DisplayClass6_0.<<Send>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at Jellyfin.Plugin.Bangumi.BangumiApi.Get[T](String url, String accessToken, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.Get[T](String url, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.GetSubject(Int32 id, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.Providers.SeriesProvider.GetSearchResults(SeriesInfo searchInfo, CancellationToken token)
   at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)
[2024-11-02 12:25:04.534 +08:00] [INF] [3] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-11-02 12:27:40.521 +08:00] [INF] [18] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
``` 
```

[2024-11-02 12:32:19.133 +08:00] [ERR] [36] MediaBrowser.Providers.Manager.ProviderManager: Provider "Bangumi" failed to retrieve search results
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Unable to read data from the transport connection: 远程主机强迫关闭了一个现有的连接。.
 ---> System.Net.Sockets.SocketException (10054): 远程主机强迫关闭了一个现有的连接。
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendWithOutCache(HttpRequestMessage request, String accessToken, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.Post(String url, HttpContent content, String accessToken, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.Post[T](String url, HttpContent content, String accessToken, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SearchSubject(String keyword, Nullable`1 type, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.Providers.SeriesProvider.GetSearchResults(SeriesInfo searchInfo, CancellationToken token)
   at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)
[2024-11-02 12:32:19.159 +08:00] [ERR] [17] MediaBrowser.Providers.Manager.ProviderManager: Provider "AniSearch" failed to retrieve search results
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Unable to read data from the transport connection: 远程主机强迫关闭了一个现有的连接。.
 ---> System.Net.Sockets.SocketException (10054): 远程主机强迫关闭了一个现有的连接。
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Jellyfin.Plugin.AniSearch.Providers.AniSearch.AniSearchApi.Search_GetSeries_list(String title, CancellationToken cancellationToken)
   at Jellyfin.Plugin.AniSearch.Providers.AniSearch.AniSearchSeriesProvider.GetSearchResults(SeriesInfo searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)
[2024-11-02 12:32:19.181 +08:00] [ERR] [43] MediaBrowser.Providers.Manager.ProviderManager: Provider "AniList" failed to retrieve search results
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Unable to read data from the transport connection: 远程主机强迫关闭了一个现有的连接。.
 ---> System.Net.Sockets.SocketException (10054): 远程主机强迫关闭了一个现有的连接。
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jellyfin.Plugin.AniList.Providers.AniList.AniListApi.WebRequestAPI(GraphQlRequest request, CancellationToken cancellationToken)
   at Jellyfin.Plugin.AniList.Providers.AniList.AniListApi.Search_GetSeries_list(String title, CancellationToken cancellationToken)
   at Jellyfin.Plugin.AniList.Providers.AniList.AniListSeriesProvider.GetSearchResults(SeriesInfo searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)
[2024-11-02 12:32:21.333 +08:00] [ERR] [17] MediaBrowser.Providers.Manager.ProviderManager: Provider "AniDB" failed to retrieve search results
System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync_ReadData(Boolean needMoreChars)
   at System.Xml.AsyncHelper.CallBoolTaskFuncWhenFinishCoreAsync[TArg](Task task, Func`2 func, TArg arg)
   at System.Xml.XmlReader.MoveToContentAsync()
   at Jellyfin.Plugin.AniDB.Providers.AniDB.Metadata.AniDbSeriesProvider.ExtractEpisodes(String seriesDataDirectory, String seriesDataPath)
   at Jellyfin.Plugin.AniDB.Providers.AniDB.Metadata.AniDbSeriesProvider.DownloadSeriesData(String aid, String seriesDataPath, String cachePath, CancellationToken cancellationToken)
   at Jellyfin.Plugin.AniDB.Providers.AniDB.Metadata.AniDbSeriesProvider.GetSeriesData(IApplicationPaths appPaths, String seriesId, CancellationToken cancellationToken)
   at Jellyfin.Plugin.AniDB.Providers.AniDB.Metadata.AniDbSeriesProvider.GetMetadataForId(String animeId, SeriesInfo info, CancellationToken cancellationToken)
   at Jellyfin.Plugin.AniDB.Providers.AniDB.Metadata.AniDbSeriesProvider.GetSearchResultsByName(String name, SeriesInfo searchInfo, CancellationToken cancellationToken)
   at Jellyfin.Plugin.AniDB.Providers.AniDB.Metadata.AniDbSeriesProvider.GetSearchResults(SeriesInfo searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)

```

**Comment by kookxiang** [comment]
看提示是 temp 下的文件被占用了，可以重开 jellyfin 再试一下更新

**Comment by jones-187** [comment]
重启电脑，重开jellyfin，重装过了，问题仍然存在。

1、再启动前，确保了任务管理器里没有jellifin相关进程。
2、启动方式是"\jellyfin-windows-tray\Jellyfin.Windows.Tray.exe"
3、v10.9到v10.10是通过压缩包替换升级上来的，重装是用的installer覆盖安装。
4、报错后尝试去手动删除临时文件夹下的文件，能够正常删除。

**Comment by jones-187** [comment]
正好最近换了台电脑，试了下还是通用问题。

**Comment by XMoon** [comment]
最新ci版确认修复
