### ISSUE TITLE
not support

### ISSUE THREAD

**Issue by Neptep** [kookxiang/jellyfin-plugin-bangumi#24]
1.4.18用手动添加的方式，在jellyfin 10.8.0中提示not support
![image](https://user-images.githubusercontent.com/33046108/182027211-81c59fd9-812f-40c9-89e9-2fab5597ca1f.png)
![image](https://user-images.githubusercontent.com/33046108/182027225-dd1fea60-f5fa-4425-a024-dd11f2a04089.png)

**Comment by kookxiang** [comment]
麻烦发一下启动的日志，看下实际的原因

**Comment by Neptep** [comment]
> 麻烦发一下启动的日志，看下实际的原因

[2022-07-31 11:31:42.176 +00:00] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly "/config/plugins/Bangumi/Jellyfin.Plugin.Bangumi.dll". This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'Execute' in type 'Jellyfin.Plugin.Bangumi.OAuth.TokenRefreshTask' from assembly 'Jellyfin.Plugin.Bangumi, Version=1.4.18.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
System.TypeLoadException: Method 'Execute' in type 'Jellyfin.Plugin.Bangumi.OAuth.TokenRefreshTask' from assembly 'Jellyfin.Plugin.Bangumi, Version=1.4.18.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

**Comment by kookxiang** [comment]
确认下是不是 jellyfin 1.8.0 稳定版？
https://github.com/jellyfin/jellyfin/blob/v10.8.0/MediaBrowser.Model/Tasks/IScheduledTask.cs#L42
官方 1.8.0 是没有 Execute 方法的

**Comment by Neptep** [comment]
> 确认下是不是 jellyfin 1.8.0 稳定版？ https://github.com/jellyfin/jellyfin/blob/v10.8.0/MediaBrowser.Model/Tasks/IScheduledTask.cs#L42 官方 1.8.0 是没有 Execute 方法的

是群晖docker安装的nyanmisaka制作的版本
