### ISSUE TITLE
已有BangumiId的Episode, 希望可以直接从这个id获取元数据

### ISSUE THREAD

**Issue by fuxin052** [kookxiang/jellyfin-plugin-bangumi#26]
主要是为了解决一些疑难Episode的匹配问题, 实在匹配不上可以通过手动输入BangumiId来获取数据

因为bangumi的某些oad的集号真的很奇怪, 我不想改成和他一样, 但是不改又匹配不上
这时我就可以手动指定id后获取元数据

还有些oad是单独出现在一个条目里, 因为名字带有oad就会找sp的条目, 我修改文件名把其中oad去掉就能匹配, 这些我也不想改文件名

所以希望能加上这个需求, 感谢

**Comment by kookxiang** [comment]
确实最近偶尔有遇到类似的问题，我做个开关吧

**Comment by fuxin052** [comment]
感谢, 最近在整理下载的番剧, 整理时总是有不符合预期了, 费了好大一番功夫, 也没有弄好

**Comment by kookxiang** [comment]
https://ci.appveyor.com/project/kookxiang/jellyfin-plugin-bangumi/builds/44683759/artifacts
有空可以试试这个版本

**Comment by fuxin052** [comment]
可以通过id拿数据了, 很完美

只是发现之前说的一个bug还没有改好 错误信息如下
```
[2022-09-06 06:59:42.184 +00:00] [WRN] [139] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: use episode index 0 from filename "[DMHY][aria][00][BD-720P][CHS].mp4"
[2022-09-06 06:59:43.017 +00:00] [INF] [145] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: metadata for "[DMHY][aria][00][BD-720P][CHS].mp4": "<Bangumi Episode #919717: その 再び出逢える奇跡に…>"
[2022-09-06 06:59:43.018 +00:00] [ERR] [145] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in "Bangumi"
System.FormatException: String '2006' was not recognized as a valid DateTime.
   at System.DateTime.Parse(String s)
   at Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider.GetMetadata(EpisodeInfo info, CancellationToken token)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```
