### ISSUE TITLE
2023/05/04 突然无法和bangumi API同步

### ISSUE THREAD

**Issue by ausar47** [kookxiang/jellyfin-plugin-bangumi#64]
![image](https://user-images.githubusercontent.com/73766358/236192513-3eb20f11-6e59-4029-bdca-773d36790c79.png)
尝试重新授权、下载最新的5.11版本、手动打勾都无法通过API同步，不知道是不是API有变化了

**Comment by jones-187** [comment]
确实有这样的问题，查看log显示：

[2023-05-05 13:42:48.391 +08:00] [INF] [59] Jellyfin.Plugin.Bangumi.PlaybackScrobbler: report episode #1183149 status Watched to bangumi
[2023-05-05 13:42:49.239 +08:00] [ERR] [35] Jellyfin.Plugin.Bangumi.PlaybackScrobbler: report playback status failed
Jellyfin.Plugin.Bangumi.Model.ServerException: Bad Request: invalid input: episode 1183149 is not episodes of subject 387803
   at Jellyfin.Plugin.Bangumi.Model.ServerException.ThrowFrom(HttpResponseMessage response)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest(HttpRequestMessage request, String accessToken, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.UpdateEpisodeStatus(String accessToken, Int32 subjectId, Int32 episodeId, EpisodeCollectionType status, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.PlaybackScrobbler.ReportPlaybackStatus(BaseItem item, Guid userId, Boolean played)

更多例子：
	Jellyfin.Plugin.Bangumi.Model.ServerException: Bad Request: invalid input: episode 1182966 is not episodes of subject 366331
	Jellyfin.Plugin.Bangumi.Model.ServerException: Bad Request: invalid input: episode 1177315 is not episodes of subject 385209
	Jellyfin.Plugin.Bangumi.Model.ServerException: Bad Request: invalid input: episode 1153158 is not episodes of subject 386809

**Comment by kookxiang** [comment]
> Bad Request: invalid input: episode 1183149 is not episodes of subject 387803

看样子是 API 那边有问题了
https://github.com/bangumi/server/issues/346

**Comment by plsy1** [comment]
遇到了同样的问题

**Comment by fuxin052** [comment]
今天好像又不行了, 前面几部番都成功了, 后面的都是这个错
```
[2023-05-20 05:08:08.236 +00:00] [INF] [45] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Web" "10.8.9" playing "革命前夜". Stopped at "1419237" ms
[2023-05-20 05:08:10.200 +00:00] [INF] [45] Jellyfin.Plugin.Bangumi.PlaybackScrobbler: report episode #1183176 status Watched to bangumi
[2023-05-20 05:08:10.571 +00:00] [ERR] [45] Jellyfin.Plugin.Bangumi.PlaybackScrobbler: report playback status failed
Jellyfin.Plugin.Bangumi.Model.ServerException: JSON Error: can't decode request body as json or value doesn't match expected type
   at Jellyfin.Plugin.Bangumi.Model.ServerException.ThrowFrom(HttpResponseMessage response)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest(HttpRequestMessage request, String accessToken, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.UpdateEpisodeStatus(String accessToken, Int32 subjectId, Int32 episodeId, EpisodeCollectionType status, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.PlaybackScrobbler.ReportPlaybackStatus(BaseItem item, Guid userId, Boolean played)
```

**Comment by plsy1** [comment]
> 

回退到1.5.0又行了。。

**Comment by kookxiang** [comment]
> Jellyfin.Plugin.Bangumi.Model.ServerException: JSON Error: can't decode request body as json or value doesn't match expected type
>    at Jellyfin.Plugin.Bangumi.Model.ServerException.ThrowFrom(HttpResponseMessage response)
>    at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest(HttpRequestMessage request, String accessToken, CancellationToken token)
>    at Jellyfin.Plugin.Bangumi.BangumiApi.UpdateEpisodeStatus(String accessToken, Int32 subjectId, Int32 episodeId, EpisodeCollectionType status, CancellationToken token)
>    at Jellyfin.Plugin.Bangumi.PlaybackScrobbler.ReportPlaybackStatus(BaseItem item, Guid userId, Boolean played)

试了下是 https://github.com/kookxiang/jellyfin-plugin-bangumi/commit/39b4801f91f8ee1b65682ddf9645f55c43b40b98 这个问题导致的，试试新版？

**Comment by fuxin052** [comment]
> > Jellyfin.Plugin.Bangumi.Model.ServerException: JSON Error: can't decode request body as json or value doesn't match expected type
> > at Jellyfin.Plugin.Bangumi.Model.ServerException.ThrowFrom(HttpResponseMessage response)
> > at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest(HttpRequestMessage request, String accessToken, CancellationToken token)
> > at Jellyfin.Plugin.Bangumi.BangumiApi.UpdateEpisodeStatus(String accessToken, Int32 subjectId, Int32 episodeId, EpisodeCollectionType status, CancellationToken token)
> > at Jellyfin.Plugin.Bangumi.PlaybackScrobbler.ReportPlaybackStatus(BaseItem item, Guid userId, Boolean played)
> 
> 试了下是 [39b4801](https://github.com/kookxiang/jellyfin-plugin-bangumi/commit/39b4801f91f8ee1b65682ddf9645f55c43b40b98) 这个问题导致的，试试新版？

最新的可以了
