### ISSUE TITLE
续期授权、重新授权和刷新元数据时遇到问题

### ISSUE THREAD

**Issue by Lancercmd** [kookxiang/jellyfin-plugin-bangumi#70]
> System.Exception: unknown response from bangumi server: \<empty>

在启动 Jellyfin 后尝试续期授权、重新授权和刷新元数据时遇到下面的问题。
```
[2023-06-15 06:21:56.397 +00:00] [INF] [1] Main: Jellyfin version: "10.8.10"
[2023-06-15 06:21:56.436 +00:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_FFMPEG, /usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_CONFIG_DIR, /config/config]", "[JELLYFIN_DATA_DIR, /config]", "[JELLYFIN_LOG_DIR, /config/log]", "[JELLYFIN_WEB_DIR, /usr/share/jellyfin/web]"]
[2023-06-15 06:21:56.441 +00:00] [INF] [1] Main: Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll"]
[2023-06-15 06:21:56.443 +00:00] [INF] [1] Main: Operating system: "Linux"
[2023-06-15 06:21:56.443 +00:00] [INF] [1] Main: Architecture: X64
[2023-06-15 06:21:56.445 +00:00] [INF] [1] Main: 64-Bit Process: True
[2023-06-15 06:21:56.445 +00:00] [INF] [1] Main: User Interactive: True
[2023-06-15 06:21:56.445 +00:00] [INF] [1] Main: Processor count: 8
[2023-06-15 06:21:56.445 +00:00] [INF] [1] Main: Program data path: "/config"
[2023-06-15 06:21:56.446 +00:00] [INF] [1] Main: Web resources path: "/usr/share/jellyfin/web"
[2023-06-15 06:21:56.446 +00:00] [INF] [1] Main: Application directory: "/usr/lib/jellyfin/bin/"
[2023-06-15 06:21:56.688 +00:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "/root/.cache/jellyfin"
[2023-06-15 06:21:56.765 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2023-06-15 06:21:56.781 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Fastenshtein, Version=1.0.0.8, Culture=neutral, PublicKeyToken=null" from "/config/plugins/Bangumi_1.5.18.0/Fastenshtein.dll"
[2023-06-15 06:21:56.805 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed" from "/config/plugins/Bangumi_1.5.18.0/Newtonsoft.Json.dll"
[2023-06-15 06:21:56.807 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "AnitomySharp, Version=0.2.0.0, Culture=neutral, PublicKeyToken=null" from "/config/plugins/Bangumi_1.5.18.0/AnitomySharp.dll"
[2023-06-15 06:21:56.820 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Bangumi, Version=1.5.18.0, Culture=neutral, PublicKeyToken=null" from "/config/plugins/Bangumi_1.5.18.0/Jellyfin.Plugin.Bangumi.dll"
[2023-06-15 06:21:56.970 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : "[10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2023-06-15 06:21:56.971 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : "[]"
[2023-06-15 06:21:56.972 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: "[10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2023-06-15 06:21:56.989 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: "[]"
[2023-06-15 06:21:56.989 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: "[]"
[2023-06-15 06:22:01.060 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Bangumi" "1.5.18.0"
[2023-06-15 06:22:01.061 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TMDb" "10.8.10.0"
[2023-06-15 06:22:01.063 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Studio Images" "10.8.10.0"
[2023-06-15 06:22:01.064 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "OMDb" "10.8.10.0"
[2023-06-15 06:22:01.065 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "MusicBrainz" "10.8.10.0"
[2023-06-15 06:22:01.066 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AudioDB" "10.8.10.0"
[2023-06-15 06:22:01.188 +00:00] [INF] [1] Main: Kestrel listening on "Any IP4 Address"
[2023-06-15 06:22:01.858 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[2023-06-15 06:22:02.027 +00:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version "5.1.3"
[2023-06-15 06:22:02.132 +00:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "decoders": ["libdav1d", "av1", "av1_cuvid", "av1_qsv", "h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8", "libvpx", "vp8_cuvid", "vp8_qsv", "vp9", "libvpx-vp9", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "dca", "flac", "mp3", "truehd"]
[2023-06-15 06:22:02.193 +00:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "encoders": ["libx264", "h264_amf", "h264_nvenc", "h264_qsv", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "hevc_vaapi", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "libfdk_aac", "ac3", "dca", "flac", "libmp3lame", "libopus", "truehd", "libvorbis", "srt"]
[2023-06-15 06:22:02.240 +00:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available filters: ["deinterlace_qsv", "deinterlace_vaapi", "hwupload_cuda", "hwupload_vaapi", "overlay_opencl", "overlay_qsv", "overlay_vaapi", "overlay_cuda", "procamp_vaapi", "scale_cuda", "scale_opencl", "scale_qsv", "scale_vaapi", "tonemap_cuda", "tonemap_opencl", "tonemap_vaapi", "vpp_qsv", "yadif_cuda", "zscale", "alphasrc"]
[2023-06-15 06:22:02.497 +00:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["cuda", "vaapi", "qsv", "drm", "opencl", "vulkan"]
[2023-06-15 06:22:02.722 +00:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: "/usr/lib/jellyfin-ffmpeg/ffmpeg"
[2023-06-15 06:22:03.262 +00:00] [INF] [1] Main: Startup complete 0:00:07.1335335
[2023-06-15 06:22:08.989 +00:00] [ERR] [32] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "POST" "/Plugins/Bangumi/RefreshOAuthToken".
System.Exception: Invalid refresh token
   at Jellyfin.Plugin.Bangumi.OAuth.OAuthUser.Refresh(HttpClient httpClient, Guid userId, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Bangumi.OAuth.OAuthController.RefreshOAuthToken()
   at lambda_method641(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2023-06-15 06:22:16.631 +00:00] [ERR] [14] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/Plugins/Bangumi/OAuth".
System.Exception: unknown response from bangumi server: <empty>
   at Jellyfin.Plugin.Bangumi.Model.ServerException.ThrowFrom(HttpResponseMessage response)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest(HttpRequestMessage request, String accessToken, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest[T](String url, String accessToken, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.GetAccountInfo(String accessToken, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.OAuth.OAuthUser.GetProfile(BangumiApi api, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Bangumi.OAuth.OAuthController.OAuthCallback(String code, String user)
   at lambda_method649(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2023-06-15 06:22:18.696 +00:00] [ERR] [33] MediaBrowser.Providers.TV.SeriesMetadataService: Error in "Bangumi"
System.Exception: unknown response from bangumi server: <empty>
   at Jellyfin.Plugin.Bangumi.Model.ServerException.ThrowFrom(HttpResponseMessage response)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest(HttpRequestMessage request, String accessToken, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest[T](String url, String accessToken, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest[T](String url, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.GetSubject(Int32 id, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.Providers.SeriesProvider.GetMetadata(SeriesInfo info, CancellationToken token)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[2023-06-15 06:22:19.950 +00:00] [ERR] [8] MediaBrowser.Providers.TV.SeasonMetadataService: Error in "Bangumi"
System.Exception: unknown response from bangumi server: <empty>
   at Jellyfin.Plugin.Bangumi.Model.ServerException.ThrowFrom(HttpResponseMessage response)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest(HttpRequestMessage request, String accessToken, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest[T](String url, String accessToken, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest[T](String url, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.GetSubject(Int32 id, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.Providers.SeasonProvider.GetMetadata(SeasonInfo info, CancellationToken token)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[2023-06-15 06:22:20.385 +00:00] [ERR] [10] MediaBrowser.Providers.TV.SeriesMetadataService: Error in "Bangumi"
System.Exception: unknown response from bangumi server: <empty>
   at Jellyfin.Plugin.Bangumi.Model.ServerException.ThrowFrom(HttpResponseMessage response)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest(HttpRequestMessage request, String accessToken, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest[T](String url, String accessToken, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest[T](String url, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.GetSubject(Int32 id, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.Providers.SeriesProvider.GetMetadata(SeriesInfo info, CancellationToken token)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[2023-06-15 06:22:31.432 +00:00] [ERR] [33] MediaBrowser.Providers.TV.SeriesMetadataService: Error in "Bangumi"
System.Exception: unknown response from bangumi server: <empty>
   at Jellyfin.Plugin.Bangumi.Model.ServerException.ThrowFrom(HttpResponseMessage response)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest(HttpRequestMessage request, String accessToken, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest[T](String url, String accessToken, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest[T](String url, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.GetSubject(Int32 id, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.Providers.SeriesProvider.GetMetadata(SeriesInfo info, CancellationToken token)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[2023-06-15 06:22:32.117 +00:00] [ERR] [28] MediaBrowser.Providers.TV.SeriesMetadataService: Error in "Bangumi"
System.Exception: unknown response from bangumi server: <empty>
   at Jellyfin.Plugin.Bangumi.Model.ServerException.ThrowFrom(HttpResponseMessage response)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest(HttpRequestMessage request, String accessToken, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest[T](String url, String accessToken, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest[T](String url, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.GetSubject(Int32 id, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.Providers.SeriesProvider.GetMetadata(SeriesInfo info, CancellationToken token)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[2023-06-15 06:22:32.662 +00:00] [ERR] [24] MediaBrowser.Providers.TV.SeasonMetadataService: Error in "Bangumi"
System.Exception: unknown response from bangumi server: <empty>
   at Jellyfin.Plugin.Bangumi.Model.ServerException.ThrowFrom(HttpResponseMessage response)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest(HttpRequestMessage request, String accessToken, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest[T](String url, String accessToken, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest[T](String url, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.GetSubject(Int32 id, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.Providers.SeasonProvider.GetMetadata(SeasonInfo info, CancellationToken token)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[2023-06-15 06:22:34.413 +00:00] [ERR] [33] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in "Bangumi"
System.Exception: unknown response from bangumi server: <empty>
   at Jellyfin.Plugin.Bangumi.Model.ServerException.ThrowFrom(HttpResponseMessage response)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest(HttpRequestMessage request, String accessToken, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest[T](String url, String accessToken, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest[T](String url, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.GetSubjectEpisodeListWithOffset(Int32 id, Nullable`1 type, Double offset, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.GetSubjectEpisodeList(Int32 id, Nullable`1 type, Double episodeNumber, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider.GetEpisode(EpisodeInfo info, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider.GetMetadata(EpisodeInfo info, CancellationToken token)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[2023-06-15 06:22:35.434 +00:00] [ERR] [24] MediaBrowser.Providers.TV.SeriesMetadataService: Error in "Bangumi"
System.Exception: unknown response from bangumi server: <empty>
   at Jellyfin.Plugin.Bangumi.Model.ServerException.ThrowFrom(HttpResponseMessage response)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest(HttpRequestMessage request, String accessToken, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest[T](String url, String accessToken, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest[T](String url, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.GetSubject(Int32 id, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.Providers.SeriesProvider.GetMetadata(SeriesInfo info, CancellationToken token)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```

**Comment by pefnpeng** [comment]
更新版本后也出现类似的问题。
2023-06-15 19:43:47.922 +08:00] [ERR] [97] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in "Bangumi"
System.Exception: unknown response from bangumi server: <empty>
   at Jellyfin.Plugin.Bangumi.Model.ServerException.ThrowFrom(HttpResponseMessage response)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest(HttpRequestMessage request, String accessToken, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest[T](String url, String accessToken, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest[T](String url, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.GetSubjectEpisodeListWithOffset(Int32 id, Nullable`1 type, Double offset, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.GetSubjectEpisodeList(Int32 id, Nullable`1 type, Double episodeNumber, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider.GetEpisode(EpisodeInfo info, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider.GetMetadata(EpisodeInfo info, CancellationToken token)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[2023-06-15 19:43:48.530 +08:00] [WRN] [62] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: file "[KissSub&Romanticat][Bofuri S2][05][1080P][GB][MP4].mp4" may has incorrect episode index 0, should be 5
[2023-06-15 19:43:48.831 +08:00] [ERR] [94] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in "Bangumi"
System.Exception: unknown response from bangumi server: <empty>
   at Jellyfin.Plugin.Bangumi.Model.ServerException.ThrowFrom(HttpResponseMessage response)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest(HttpRequestMessage request, String accessToken, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest[T](String url, String accessToken, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest[T](String url, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.GetSubjectEpisodeListWithOffset(Int32 id, Nullable`1 type, Double offset, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.GetSubjectEpisodeList(Int32 id, Nullable`1 type, Double episodeNumber, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider.GetEpisode(EpisodeInfo info, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider.GetMetadata(EpisodeInfo info, CancellationToken token)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[2023-06-15 19:43:49.499 +08:00] [WRN] [62] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: file "[KissSub&Romanticat][Bofuri S2][06][1080P][GB][MP4].mp4" may has incorrect episode index 0, should be 6
[2023-06-15 19:43:50.397 +08:00] [ERR] [97] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in "Bangumi"
System.Exception: unknown response from bangumi server: <empty>
   at Jellyfin.Plugin.Bangumi.Model.ServerException.ThrowFrom(HttpResponseMessage response)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest(HttpRequestMessage request, String accessToken, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest[T](String url, String accessToken, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest[T](String url, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.GetSubjectEpisodeListWithOffset(Int32 id, Nullable`1 type, Double offset, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.GetSubjectEpisodeList(Int32 id, Nullable`1 type, Double episodeNumber, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider.GetEpisode(EpisodeInfo info, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider.GetMetadata(EpisodeInfo info, CancellationToken token)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, T

**Comment by kookxiang** [comment]
https://api.bgm.tv/v0/episodes/386557
API 好像挂了

**Comment by pefnpeng** [comment]
oh，no。那只能等它恢复了

**Comment by li-guohao** [comment]
Jellyfin v10.9.2 授权返回URL时会出现问题，需要在URL前加上 `/Plugins` 在这里记录下，方便后面遇到问题的朋友参考。

修改前：`http://doman:port/Bangumi/OAuth?user=xxx&code=xxx`
=>
修改后：`http://doman:port/Plugins/Bangumi/OAuth?user=xxx&code=xxx`

**Comment by Lancercmd** [comment]
> Jellyfin `v10.9.2` 授权返回URL时会出现问题，需要在URL前加上 `/Plugins` 在这里记录下，方便后面遇到问题的朋友参考。
> 
> 修改前：`http://doman:port/Bangumi/OAuth?user=xxx&code=xxx` => 修改后：`http://doman:port/Plugins/Bangumi/OAuth?user=xxx&code=xxx`

对于 Jellyfin 版本 `10.9.x` 现可以更新 Bangumi 插件到 `1.6.1.0` 后解决。
