### ISSUE TITLE
插件获取元数据报错

### ISSUE THREAD

**Issue by Archer-Tatsu** [kookxiang/jellyfin-plugin-bangumi#72]
确认网络无问题，尝试加减梯子都是一样的效果，怀疑是不是api啥的有变化，之前一直都正常的……
```
[2023-06-23 13:29:43.026 +08:00] [ERR] [24] MediaBrowser.Providers.TV.SeasonMetadataService: Error in "Bangumi"
System.Text.Json.JsonException: The JSON value could not be converted to System.Collections.Generic.List`1[Jellyfin.Plugin.Bangumi.Model.RelatedPerson]. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest[T](String url, String accessToken, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest[T](String url, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.GetSubjectPersons(Int32 id, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.GetSubjectPersonInfos(Int32 id, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.Providers.SeasonProvider.GetMetadata(SeasonInfo info, CancellationToken token)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[2023-06-23 13:29:44.951 +08:00] [ERR] [24] MediaBrowser.Providers.TV.SeasonMetadataService: Error in "Bangumi"
System.InvalidOperationException: An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.
   at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)
   at System.Net.Http.HttpClient.CheckRequestBeforeSend(HttpRequestMessage request)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetAsync(String requestUri, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Bangumi.Providers.SubjectImageProvider.GetImageResponse(String url, CancellationToken token)
   at MediaBrowser.Providers.Manager.ItemImageProvider.DownloadImage(BaseItem item, IRemoteImageProvider provider, RefreshResult result, IEnumerable`1 images, Int32 minWidth, ImageType type, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ItemImageProvider.RefreshFromProvider(BaseItem item, IRemoteImageProvider provider, ImageRefreshOptions refreshOptions, TypeOptions savedOptions, Int32 backdropLimit, ICollection`1 downloadedImages, RefreshResult result, CancellationToken cancellationToken)

```

**Comment by fuxin052** [comment]
我看了下是api全部404了

**Comment by fuxin052** [comment]
![image](https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/46592199/4e6674e3-7017-46df-b97a-cb46e7609eb0)
![image](https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/46592199/69ccf618-2dd1-49d4-b607-87600963a71d)

**Comment by TnZzZHlp** [comment]
我也遇到了，看了下bgm好像也没人提

**Comment by Archer-Tatsu** [comment]
https://github.com/bangumi/api/issues/189 修了
