### ISSUE TITLE
无法正常识别和设置季

### ISSUE THREAD

**Issue by qianxuu** [kookxiang/jellyfin-plugin-bangumi#78]
如题，所有集都被设置成了季0
![image](https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/62287903/144c17e1-dea7-4c8e-87e0-192b28b7ab63)
![image](https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/62287903/4a16a769-78ad-441b-83f4-c364ef87f7be)
![image](https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/62287903/20114be2-b898-487f-b9ca-bb0c70855a7d)

**Comment by chu-shen** [comment]
之前是不是识别失败过，识别成其他的了？

如果是的话可能与这段代码有关

https://github.com/kookxiang/jellyfin-plugin-bangumi/blob/5ac027314f35c65bab36a47f19d20b60cbb840d9/Jellyfin.Plugin.Bangumi/Providers/EpisodeProvider.cs#L99

**Comment by qianxuu** [comment]
> 之前是不是识别失败过，识别成其他的了？
> 
> 如果是的话可能与这段代码有关
> 
> https://github.com/kookxiang/jellyfin-plugin-bangumi/blob/5ac027314f35c65bab36a47f19d20b60cbb840d9/Jellyfin.Plugin.Bangumi/Providers/EpisodeProvider.cs#L99

这个媒体库只勾选了 bangumi，对了，我先用了 tmm 来搜刮改名，附带了 nfo，是这个原因吗

**Comment by qianxuu** [comment]
使用 bangumi 填写 id 识别前，季集是 tmm 刮削的 anidb 数据
![image](https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/62287903/a068fd15-ea94-4ffe-a9db-aad69ddf6df8)
使用 bangumi 识别之后
![image](https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/62287903/7751665c-f04a-41d5-ab72-0adf89dd9bab)
![image](https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/62287903/8f06f91e-e610-4c62-b173-ade8e8d2aa5b)

**Comment by qianxuu** [comment]
bangumi 设置：
![image](https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/62287903/c790c48d-9a7b-485a-88a4-4731a2d23894)

nfo（github 上传限制，我将后缀改成了 txt）：
[And You Thought There Is Never a Girl Online - S01E01 - And You Thought There Is Never a Girl Online.txt](https://github.com/kookxiang/jellyfin-plugin-bangumi/files/12122270/And.You.Thought.There.Is.Never.a.Girl.Online.-.S01E01.-.And.You.Thought.There.Is.Never.a.Girl.Online.txt)

文件名：
And You Thought There Is Never a Girl Online - S01E01 - And You Thought There Is Never a Girl Online.mkv

**Comment by qianxuu** [comment]
> 麻烦贴下 bangumi 配置，另外分享下 nfo 和文件名
> 
> 试下不使用 nfo， 直接添加会不会有同样的问题

试了一下把 nfo 全删了，依旧是被设置成季 0

**Comment by kookxiang** [comment]
勾选一下始终根据文件名猜测集数试试
另外用外部工具生成 nfo 后要检查下生成的 nfo 文件 jellyfin 是否可写

**Comment by qianxuu** [comment]
> 勾选一下始终根据文件名猜测集数试试 另外用外部工具生成 nfo 后要检查下生成的 nfo 文件 jellyfin 是否可写

勾选后依旧被设置成了季 0，外部 nfo 已删除，jellyfin 容器给了特权，媒体库的这两个功能均没有打开，和外部应该没啥关系？
![image](https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/62287903/83577bff-47ca-434e-8408-2821f0a1a85b)
![image](https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/62287903/d7beaa28-a8ea-4f22-989a-37129784e0c0)

**Comment by kookxiang** [comment]
麻烦发一下后台的日志，应该有识别集号的内容

**Comment by qianxuu** [comment]
> 麻烦发一下后台的日志，应该有识别集号的内容

```
[2023-07-21 11:00:43.326 +00:00] [INF] [95] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.1.210" request
[2023-07-21 11:01:24.441 +00:00] [INF] [42] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "扫描媒体库"
[2023-07-21 11:01:24.444 +00:00] [INF] [42] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "/HDD/Videos/Anime"
[2023-07-21 11:01:24.445 +00:00] [INF] [42] Emby.Server.Implementations.Library.LibraryManager: Validating media library
[2023-07-21 11:01:24.617 +00:00] [INF] [23] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Series", Name: "线上游戏的老婆不可能是女生？", Path: "/HDD/Videos/Anime/And You Thought There Is Never a Girl Online (2016)", Id: e3bac5d1-46e8-c98d-8857-1183b514ebfd
[2023-07-21 11:01:25.551 +00:00] [ERR] [44] Emby.Server.Implementations.Library.LibraryManager: Error running post-scan task
System.ArgumentException: Not enough valid pictures provided to create a splashscreen!
   at Jellyfin.Drawing.Skia.SplashscreenBuilder.GenerateCollage(IReadOnlyList`1 posters, IReadOnlyList`1 backdrops)
   at Jellyfin.Drawing.Skia.SplashscreenBuilder.GenerateSplash(IReadOnlyList`1 posters, IReadOnlyList`1 backdrops, String outputPath)
   at Jellyfin.Drawing.Skia.SkiaEncoder.CreateSplashscreen(IReadOnlyList`1 posters, IReadOnlyList`1 backdrops)
   at Emby.Server.Implementations.Library.SplashscreenPostScanTask.Run(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.RunPostScanTasks(IProgress`1 progress, CancellationToken cancellationToken)
[2023-07-21 11:01:25.656 +00:00] [INF] [44] Emby.Server.Implementations.ScheduledTasks.TaskManager: "扫描媒体库" Completed after 0 minute(s) and 1 seconds
[2023-07-21 11:01:25.661 +00:00] [INF] [44] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[2023-07-21 11:01:25.910 +00:00] [INF] [64] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/HDD/Videos/Anime"
[2023-07-21 11:01:37.446 +00:00] [INF] [44] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "扫描媒体库"
[2023-07-21 11:01:37.449 +00:00] [INF] [44] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "/HDD/Videos/Anime"
[2023-07-21 11:01:37.450 +00:00] [INF] [44] Emby.Server.Implementations.Library.LibraryManager: Validating media library
[2023-07-21 11:01:38.115 +00:00] [INF] [23] Jellyfin.Plugin.Bangumi.Providers.SeriesProvider: Searching "And You Thought There Is Never a Girl Online (2016)" in bgm.tv
[2023-07-21 11:01:38.988 +00:00] [INF] [42] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: metadata for "And You Thought There Is Never a Girl Online - S01E01 - And You Thought There Is Never a Girl Online.mkv": null
[2023-07-21 11:01:39.195 +00:00] [INF] [23] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: metadata for "And You Thought There Is Never a Girl Online - S01E05 - I Thought Reincarnating Would Give Me My Big Chance.mkv": null
[2023-07-21 11:01:39.395 +00:00] [INF] [23] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: metadata for "And You Thought There Is Never a Girl Online - S01E08 - I Thought I Was Giving Up Being a Net Game Husband.mkv": null
[2023-07-21 11:01:39.603 +00:00] [INF] [44] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: metadata for "And You Thought There Is Never a Girl Online - S01E09 - I Thought If We Stayed Over, We Would Get Along Better.mkv": null
[2023-07-21 11:01:39.808 +00:00] [INF] [64] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: metadata for "And You Thought There Is Never a Girl Online - S01E12 - My Net Game Wife Is a Girl Online!.mkv": null
[2023-07-21 11:01:40.008 +00:00] [INF] [83] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: metadata for "And You Thought There Is Never a Girl Online - S01E02 - I Thought We Couldn`t Play Net Games at School.mkv": null
[2023-07-21 11:01:40.212 +00:00] [INF] [42] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: metadata for "And You Thought There Is Never a Girl Online - S01E10 - I Thought We Would Do Our Best at the Culture Festival.mkv": null
[2023-07-21 11:01:40.418 +00:00] [INF] [44] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: metadata for "And You Thought There Is Never a Girl Online - S01E03 - I Thought Net Games and Reality Were Different.mkv": null
[2023-07-21 11:01:40.632 +00:00] [INF] [23] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: metadata for "And You Thought There Is Never a Girl Online - S01E07 - I Thought If I Went to the Beach, I Would Become a Normie.mkv": null
[2023-07-21 11:01:40.834 +00:00] [INF] [83] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: metadata for "And You Thought There Is Never a Girl Online - S01E11 - I Thought We Could Win by Delegating to Others.mkv": null
[2023-07-21 11:01:41.044 +00:00] [INF] [10] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: metadata for "And You Thought There Is Never a Girl Online - S01E06 - I Thought If I Declared My Love, I Was Sure to Succeed.mkv": null
[2023-07-21 11:01:41.241 +00:00] [INF] [42] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: metadata for "And You Thought There Is Never a Girl Online - S01E04 - I Thought Her Secret Wasn`t Going to Get Out.mkv": null
[2023-07-21 11:01:41.340 +00:00] [ERR] [10] Emby.Server.Implementations.Library.LibraryManager: Error running post-scan task
System.ArgumentException: Not enough valid pictures provided to create a splashscreen!
   at Jellyfin.Drawing.Skia.SplashscreenBuilder.GenerateCollage(IReadOnlyList`1 posters, IReadOnlyList`1 backdrops)
   at Jellyfin.Drawing.Skia.SplashscreenBuilder.GenerateSplash(IReadOnlyList`1 posters, IReadOnlyList`1 backdrops, String outputPath)
   at Jellyfin.Drawing.Skia.SkiaEncoder.CreateSplashscreen(IReadOnlyList`1 posters, IReadOnlyList`1 backdrops)
   at Emby.Server.Implementations.Library.SplashscreenPostScanTask.Run(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.RunPostScanTasks(IProgress`1 progress, CancellationToken cancellationToken)
[2023-07-21 11:01:41.433 +00:00] [INF] [10] Emby.Server.Implementations.ScheduledTasks.TaskManager: "扫描媒体库" Completed after 0 minute(s) and 3 seconds
[2023-07-21 11:01:41.436 +00:00] [INF] [10] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[2023-07-21 11:01:41.583 +00:00] [INF] [83] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/HDD/Videos/Anime"
[2023-07-21 11:01:55.535 +00:00] [INF] [23] Jellyfin.Api.Controllers.ItemLookupController: Setting provider id's to item e3bac5d1-46e8-c98d-8857-1183b514ebfd-"And You Thought There Is Never a Girl Online (2016)": "{\"Bangumi\":\"142758\"}"
[2023-07-21 11:02:01.471 +00:00] [WRN] [10] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: use episode index 1 from filename "And You Thought There Is Never a Girl Online - S01E01 - And You Thought There Is Never a Girl Online.mkv"
[2023-07-21 11:02:01.725 +00:00] [WRN] [44] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: use episode index 1 from filename "And You Thought There Is Never a Girl Online - S01E01 - And You Thought There Is Never a Girl Online.mkv"
[2023-07-21 11:02:01.726 +00:00] [INF] [44] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: metadata for "And You Thought There Is Never a Girl Online - S01E01 - And You Thought There Is Never a Girl Online.mkv": "<Bangumi Episode #617729: ネトゲの嫁は女の子じゃないと思った？>"
[2023-07-21 11:02:02.209 +00:00] [WRN] [44] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: use episode index 5 from filename "And You Thought There Is Never a Girl Online - S01E05 - I Thought Reincarnating Would Give Me My Big Chance.mkv"
[2023-07-21 11:02:02.450 +00:00] [WRN] [44] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: use episode index 5 from filename "And You Thought There Is Never a Girl Online - S01E05 - I Thought Reincarnating Would Give Me My Big Chance.mkv"
[2023-07-21 11:02:02.451 +00:00] [INF] [44] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: metadata for "And You Thought There Is Never a Girl Online - S01E05 - I Thought Reincarnating Would Give Me My Big Chance.mkv": "<Bangumi Episode #617733: 転生すればワンチャンあると思った？>"
[2023-07-21 11:02:02.935 +00:00] [WRN] [10] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: use episode index 8 from filename "And You Thought There Is Never a Girl Online - S01E08 - I Thought I Was Giving Up Being a Net Game Husband.mkv"
[2023-07-21 11:02:03.184 +00:00] [WRN] [10] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: use episode index 8 from filename "And You Thought There Is Never a Girl Online - S01E08 - I Thought I Was Giving Up Being a Net Game Husband.mkv"
[2023-07-21 11:02:03.184 +00:00] [INF] [10] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: metadata for "And You Thought There Is Never a Girl Online - S01E08 - I Thought I Was Giving Up Being a Net Game Husband.mkv": "<Bangumi Episode #617736: ネトゲの旦那を諦めると思った？>"
[2023-07-21 11:02:03.664 +00:00] [WRN] [23] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: use episode index 9 from filename "And You Thought There Is Never a Girl Online - S01E09 - I Thought If We Stayed Over, We Would Get Along Better.mkv"
[2023-07-21 11:02:03.905 +00:00] [WRN] [23] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: use episode index 9 from filename "And You Thought There Is Never a Girl Online - S01E09 - I Thought If We Stayed Over, We Would Get Along Better.mkv"
[2023-07-21 11:02:03.905 +00:00] [INF] [23] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: metadata for "And You Thought There Is Never a Girl Online - S01E09 - I Thought If We Stayed Over, We Would Get Along Better.mkv": "<Bangumi Episode #617737: お泊まりしたら仲良くなれると思った？>"
[2023-07-21 11:02:04.373 +00:00] [WRN] [10] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: use episode index 12 from filename "And You Thought There Is Never a Girl Online - S01E12 - My Net Game Wife Is a Girl Online!.mkv"
[2023-07-21 11:02:04.639 +00:00] [WRN] [44] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: use episode index 12 from filename "And You Thought There Is Never a Girl Online - S01E12 - My Net Game Wife Is a Girl Online!.mkv"
[2023-07-21 11:02:04.640 +00:00] [INF] [44] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: metadata for "And You Thought There Is Never a Girl Online - S01E12 - My Net Game Wife Is a Girl Online!.mkv": "<Bangumi Episode #617740: ネトゲの嫁は女の子なんですよ！>"
[2023-07-21 11:02:05.116 +00:00] [WRN] [23] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: use episode index 2 from filename "And You Thought There Is Never a Girl Online - S01E02 - I Thought We Couldn`t Play Net Games at School.mkv"
[2023-07-21 11:02:05.722 +00:00] [WRN] [23] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: use episode index 2 from filename "And You Thought There Is Never a Girl Online - S01E02 - I Thought We Couldn`t Play Net Games at School.mkv"
[2023-07-21 11:02:05.723 +00:00] [INF] [23] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: metadata for "And You Thought There Is Never a Girl Online - S01E02 - I Thought We Couldn`t Play Net Games at School.mkv": "<Bangumi Episode #617730: 学校じゃネトグはできないと思った？>"
[2023-07-21 11:02:06.207 +00:00] [WRN] [44] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: use episode index 10 from filename "And You Thought There Is Never a Girl Online - S01E10 - I Thought We Would Do Our Best at the Culture Festival.mkv"
[2023-07-21 11:02:06.794 +00:00] [WRN] [10] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: use episode index 10 from filename "And You Thought There Is Never a Girl Online - S01E10 - I Thought We Would Do Our Best at the Culture Festival.mkv"
[2023-07-21 11:02:06.795 +00:00] [INF] [10] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: metadata for "And You Thought There Is Never a Girl Online - S01E10 - I Thought We Would Do Our Best at the Culture Festival.mkv": "<Bangumi Episode #617738: 文化祭なら頑張ると思った？>"
[2023-07-21 11:02:07.289 +00:00] [WRN] [10] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: use episode index 3 from filename "And You Thought There Is Never a Girl Online - S01E03 - I Thought Net Games and Reality Were Different.mkv"
[2023-07-21 11:02:07.546 +00:00] [WRN] [10] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: use episode index 3 from filename "And You Thought There Is Never a Girl Online - S01E03 - I Thought Net Games and Reality Were Different.mkv"
[2023-07-21 11:02:07.547 +00:00] [INF] [10] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: metadata for "And You Thought There Is Never a Girl Online - S01E03 - I Thought Net Games and Reality Were Different.mkv": "<Bangumi Episode #617731: ネトゲとリアルは違うと思った？>"
[2023-07-21 11:02:08.046 +00:00] [WRN] [23] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: use episode index 7 from filename "And You Thought There Is Never a Girl Online - S01E07 - I Thought If I Went to the Beach, I Would Become a Normie.mkv"
[2023-07-21 11:02:08.292 +00:00] [WRN] [83] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: use episode index 7 from filename "And You Thought There Is Never a Girl Online - S01E07 - I Thought If I Went to the Beach, I Would Become a Normie.mkv"
[2023-07-21 11:02:08.293 +00:00] [INF] [83] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: metadata for "And You Thought There Is Never a Girl Online - S01E07 - I Thought If I Went to the Beach, I Would Become a Normie.mkv": "<Bangumi Episode #617735: 海に行ったらリア充になれると思った？>"
[2023-07-21 11:02:08.760 +00:00] [WRN] [83] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: use episode index 11 from filename "And You Thought There Is Never a Girl Online - S01E11 - I Thought We Could Win by Delegating to Others.mkv"
[2023-07-21 11:02:08.994 +00:00] [WRN] [44] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: use episode index 11 from filename "And You Thought There Is Never a Girl Online - S01E11 - I Thought We Could Win by Delegating to Others.mkv"
[2023-07-21 11:02:08.996 +00:00] [INF] [44] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: metadata for "And You Thought There Is Never a Girl Online - S01E11 - I Thought We Could Win by Delegating to Others.mkv": "<Bangumi Episode #617739: 他人任せで勝てると思った?>"
[2023-07-21 11:02:09.464 +00:00] [WRN] [10] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: use episode index 6 from filename "And You Thought There Is Never a Girl Online - S01E06 - I Thought If I Declared My Love, I Was Sure to Succeed.mkv"
[2023-07-21 11:02:09.713 +00:00] [WRN] [44] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: use episode index 6 from filename "And You Thought There Is Never a Girl Online - S01E06 - I Thought If I Declared My Love, I Was Sure to Succeed.mkv"
[2023-07-21 11:02:09.714 +00:00] [INF] [44] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: metadata for "And You Thought There Is Never a Girl Online - S01E06 - I Thought If I Declared My Love, I Was Sure to Succeed.mkv": "<Bangumi Episode #617734: 告白したら成功確定だと思った？>"
[2023-07-21 11:02:10.187 +00:00] [WRN] [87] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: use episode index 4 from filename "And You Thought There Is Never a Girl Online - S01E04 - I Thought Her Secret Wasn`t Going to Get Out.mkv"
[2023-07-21 11:02:10.432 +00:00] [WRN] [87] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: use episode index 4 from filename "And You Thought There Is Never a Girl Online - S01E04 - I Thought Her Secret Wasn`t Going to Get Out.mkv"
[2023-07-21 11:02:10.432 +00:00] [INF] [87] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: metadata for "And You Thought There Is Never a Girl Online - S01E04 - I Thought Her Secret Wasn`t Going to Get Out.mkv": "<Bangumi Episode #617732: あの子の秘密がバレないと思った？>"
[2023-07-21 11:02:11.937 +00:00] [WRN] [83] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://192.168.1.200:8096/Items/RemoteSearch/Apply/e3bac5d146e8c98d88571183b514ebfd?ReplaceAllImages=true" to "192.168.1.210" in 0:00:16.4086375 with Status Code 204
[2023-07-21 11:07:31.356 +00:00] [INF] [72] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2023-07-21 11:07:43.356 +00:00] [INF] [81] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2023-07-21 11:09:31.357 +00:00] [INF] [72] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2023-07-21 11:09:43.357 +00:00] [INF] [43] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2023-07-21 11:09:55.358 +00:00] [INF] [72] Emby.Server.Implementations.Session.SessionWebSocketListener: Lost 1 WebSockets.
```

**Comment by kookxiang** [comment]
```
[2023-07-21 11:02:10.187 +00:00] [WRN] [87] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: use episode index 4 from filename "And You Thought There Is Never a Girl Online - S01E04 - I Thought Her Secret Wasn`t Going to Get Out.mkv"
[2023-07-21 11:02:10.432 +00:00] [WRN] [87] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: use episode index 4 from filename "And You Thought There Is Never a Girl Online - S01E04 - I Thought Her Secret Wasn`t Going to Get Out.mkv"
[2023-07-21 11:02:10.432 +00:00] [INF] [87] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: metadata for "And You Thought There Is Never a Girl Online - S01E04 - I Thought Her Secret Wasn`t Going to Get Out.mkv": "<Bangumi Episode #617732: あの子の秘密がバレないと思った？>"
```

看日志是识别成功了

**Comment by qianxuu** [comment]
> ```
> [2023-07-21 11:02:10.187 +00:00] [WRN] [87] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: use episode index 4 from filename "And You Thought There Is Never a Girl Online - S01E04 - I Thought Her Secret Wasn`t Going to Get Out.mkv"
> [2023-07-21 11:02:10.432 +00:00] [WRN] [87] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: use episode index 4 from filename "And You Thought There Is Never a Girl Online - S01E04 - I Thought Her Secret Wasn`t Going to Get Out.mkv"
> [2023-07-21 11:02:10.432 +00:00] [INF] [87] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: metadata for "And You Thought There Is Never a Girl Online - S01E04 - I Thought Her Secret Wasn`t Going to Get Out.mkv": "<Bangumi Episode #617732: あの子の秘密がバレないと思った？>"
> ```
> 
> 看日志是识别成功了

我在元数据里面看了一下，在手动用 bangumi 识别前，季目录和集都有正常的号码 1，识别之后集号全部变成了 0，季目录的号码变成了空


前：
![image](https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/62287903/7d0a3928-d540-48d8-95ab-e6570efd7417)
![image](https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/62287903/d4d9e669-6a2f-446c-8290-dce528ceb574)

后：
![image](https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/62287903/8767f221-1cd6-4b23-a6a1-1e77488af681)
![image](https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/62287903/836e00a5-53f5-468b-a85d-a8cd2cc2af00)

**Comment by kookxiang** [comment]
试试先刷新下季的元数据？

**Comment by chu-shen** [comment]
我这边测试没有问题，能够正常识别为第一季。

媒体库里所有系列都有这问题吗？刷新元数据时，模式选择覆盖所有元数据

**Comment by qianxuu** [comment]
> 我这边测试没有问题，能够正常识别为第一季。
> 
> 媒体库里所有系列都有这问题吗？刷新元数据时，模式选择覆盖所有元数据

我刚刚测试了一下，大概知道啥问题了，如果直接用这个 `识别` 就会变成季 0，编辑元数据填 id 再刷新选覆盖就没事
![image](https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/62287903/263c6c21-176c-40ad-a523-3042782726d0)

**Comment by qianxuu** [comment]
> 我这边测试没有问题，能够正常识别为第一季。
> 
> 媒体库里所有系列都有这问题吗？刷新元数据时，模式选择覆盖所有元数据
> 
> 另外插件是最新版本吗👉https://ci.appveyor.com/project/kookxiang/jellyfin-plugin-bangumi/builds/47504973/artifacts

插件是存储库里的最新版 `1.5.18.0`

**Comment by qianxuu** [comment]
已正常使用，文件名能和 bangumi 自动匹配上的，会自动在元数据加入 bangumi id，匹配不上的，手动编辑元数据设置 id，然后全选，刷新+覆盖，就能完美了，不能直接用 `识别` 功能
![image](https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/62287903/a65b7e0c-0863-4963-982a-c2786d206e49)
![image](https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/62287903/201fffd3-deb4-4e87-bbfb-15d360604f7f)
