### ISSUE TITLE
无法授权登录Bangumi

### ISSUE THREAD

**Issue by sakuyamaij** [kookxiang/jellyfin-plugin-bangumi#87]
跳转bgm授权页面后显示
Error processing request.

`[2023-08-30 06:42:44.737 +08:00] [ERR] [59] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: "The request was canceled due to the configured HttpClient.Timeout of 5 seconds elapsing". URL "GET" "/Plugins/Bangumi/OAuth".
[2023-08-30 06:42:44.737 +08:00] [WRN] [59] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://192.168.1.202:8096/Plugins/Bangumi/OAuth?user=b6a002a32750445887c833c03f9df731&code=xxxxxxxxx" to "192.168.1.193" in 0:00:05.0040865 with Status Code 500`

**Comment by kookxiang** [comment]
挂个梯子试试？

**Comment by wzyboy** [comment]
今天我也遇到类似的错误了（刚才加了个新动画到库里），不确定什么时候开始的：

```
[ERR] [42] MediaBrowser.Providers.TV.SeriesMetadataService: Error in Bangumi
System.Net.Http.HttpRequestException: Resource temporarily unavailable (api.bgm.tv:443)
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
```

我在墙外，直接 `curl -v https://api.bgm.tv` 是没问题的…

有什么 debug 参数可以让它打印出 HTTP body 吗？

**Comment by wzyboy** [comment]
我的错误消失了，可能是 Bangumi 抽风？

不过还是可以考虑加一个网络出错时打印 HTTP body 的功能…

**Comment by kookxiang** [comment]
> 有什么 debug 参数可以让它打印出 HTTP body 吗？

这个报错是 http 连接没有建立成功，所以是没有 body 的
