### ISSUE TITLE
如何识别R18OVA

### ISSUE THREAD

**Issue by Rivers47** [kookxiang/jellyfin-plugin-bangumi#93]
失败例：Call Me トゥナイト
目录格式：
```
Call Me トゥナイト/
├── Season 01
│   ├── 01.mkv
│   ├── 01.nfo
│   └── season.nfo
└── tvshow.nfo
```
按我的理解所有的BGM条目都属于TV shows，所以这么做应该是最规范的？
把Season 01的内容平铺也一样无法识别
是BGM API的问题？但我手动搜BGM可以搜到
```
[2023-10-14 21:57:03.618 -04:00] [INF] [136] Jellyfin.Plugin.Bangumi.Providers.SeriesProvider: Searching "Call Me トゥナイト" in bgm.tv
[2023-10-14 21:57:04.075 -04:00] [ERR] [136] MediaBrowser.Providers.TV.SeriesMetadataService: Error in "Bangumi"
Jellyfin.Plugin.Bangumi.Model.ServerException: Not Found: resource can't be found in the database or has been removed
   at Jellyfin.Plugin.Bangumi.Model.ServerException.ThrowFrom(HttpResponseMessage response)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest(HttpRequestMessage request, String accessToken, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest[T](String url, String accessToken, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.SendRequest[T](String url, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.BangumiApi.GetSubject(Int32 id, CancellationToken token)
   at Jellyfin.Plugin.Bangumi.Providers.SeriesProvider.GetMetadata(SeriesInfo info, CancellationToken token)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```

**Comment by Rivers47** [comment]
啊，破案了，因为是限制级内容所以要登录账号API才能搜到。。。完全忘了这回事了

**Comment by Rivers47** [comment]
已解决
